https://stevesie.com/apps/airbnb-api/listings

In [1]:
import requests
import json
import time

In [2]:
url = "https://api.airbnb.com/v2/explore_tabs"
params = {
    'key':'d306zoyjsyarp7ifhu67rjxn52tv0t20',
    '_format':'for_explore_search_web',
    
    'currency':'KRW',
    'location':'서울',
    'tab_id':'home_tab',
    'items_per_grid':'306', # 최대 306 -> 수정할방법찾아야
#     'section_offset':'1',
#     'supports_for_you_v3':'true',
#     'timezone_offset':'300',
    'version':'1.3.9'
    }

In [31]:
resp = requests.get(url,params=params)

JSON 개념 정리

https://github.com/chankoo/python-for-data/blob/master/3.2%20JSON%2C%20XML.ipynb

In [32]:
res_jsn = resp.json() # .json() 메소드: response의 형태가 json 일경우 이 response를 파이썬 dict로 바로 매핑해준다

In [33]:
# with open('home_jsn_306.json', 'w') as fp: # 파일로 저장하자 -> review 크롤러에서 가져다 쓰기 위해서이다
#     json.dump(res_jsn,fp) # 파이썬 dict를 다시 json으로 변환하려면 json 모듈의 dump를 이용

__데이터 구조 개괄__
- res_jsn: {explore_tabs, metadata}
    -  __explore_tabs[0]__: { 'tab_id', 'tab_name', 'pagination_metadata', 'sections', 'experiments_metadata', 'home_tab_metadata'}
        - tab_id: home_tab
        - tab_name: homes
        - pagination_metadata: {'has_next_page', 'items_offset', 'section_offset', 'search_session_id'}
        - __sections: [0:not paginated, 1: paginated]__
            - sections[0]: ...'messages': [{'icon': 'icon-p2-aggregate-reviews',
                                           'style': 'MESSAGE_WITH_ICON',
                                       'title': 'Over 540,000 guest reviews for Seoul homes, with an average of 4.7 out of 5 stars.'}]...
                                       
            - __sections__[1]:{'backend_search_id', 'display_type', 'experiments_metadata', 'result_type', 'search_session_id', 'section_id', 'section_type_uid', 'title', 'is_paginated', 'bankai_section_id', 'refinements', __'listings'__, 'review_items', 'breadcrumbs', 'section_metadata', 'nearby_locations', 'localized_listing_count'}
                - ...
                - __listings: [#items_per_grid \* { {listing}, {pricing_quote}, {verified}, {verified_card} }]__
                    - __listing : 해당 숙소에 대한 50가지 features__
                - ...
        - experiments_metadata
        - home_tab_metadata: {'urgency_commitment', 'golden_ticket_urgency_commitment', 'listing_cards_urgency_commitment_metadata', 'listing_cards_price_line_urgency_commitment_metadata', 'messages', 'facets', 'overrides', 'search_feed_items', __'remarketing_ids'__, 'location', 'breadcrumbs', 'listings_count', 'search', 'geography', 'price_histogram', 'filters'}
            - __remarketing_ids__ : listing_id 담은 리스트 -> 숙소 id 바로뽑을 수 있다
  
    
    
    - metadata

In [5]:
res_jsn.keys() # 가장 큰 구조, 'explore_tabs'과 'metadata'로 나뉨

dict_keys(['explore_tabs', 'metadata'])

In [6]:
res_jsn['explore_tabs'][0].keys() # explore_tabs을 살펴보자

dict_keys(['tab_id', 'tab_name', 'pagination_metadata', 'sections', 'experiments_metadata', 'home_tab_metadata'])

In [7]:
res_jsn['explore_tabs'][0]['tab_id']
res_jsn['explore_tabs'][0]['tab_name'] # 웹에서 보고있는 탭이 homes 이다

'homes'

> home 탭으로 추정되는 화면
>![2018-11-04 13-38-47](https://user-images.githubusercontent.com/38183218/47960055-11210580-e037-11e8-865d-8f3fda99ed7b.png)

계속 살펴보자

In [8]:
# pagination 즉, 페이지가 넘어가는 것에 대한 메타데이터가 담겨있음
res_jsn['explore_tabs'][0]['pagination_metadata'] # items_per_grid 300개 이상 설정시 {'has_next_page': False} 가 떠버림

{'has_next_page': True,
 'items_offset': 100,
 'section_offset': 5,
 'search_session_id': '3cb445a2-32c0-420a-91df-b38e1c87d51e'}

In [9]:
# 본격적인 컨텐츠를 구성하는 sections[1] 의 구조
res_jsn['explore_tabs'][0]['sections'][1].keys()

dict_keys(['backend_search_id', 'display_type', 'experiments_metadata', 'result_type', 'search_session_id', 'section_id', 'section_type_uid', 'title', 'is_paginated', 'bankai_section_id', 'refinements', 'listings', 'review_items', 'breadcrumbs', 'section_metadata', 'nearby_locations', 'localized_listing_count'])

In [10]:
# listings에 숙소가 리스팅되어있다
res_jsn['explore_tabs'][0]['sections'][1]['listings'][1].keys()

dict_keys(['listing', 'pricing_quote', 'verified', 'verified_card'])

위 4가지 key중 listing에 대부분의 feature가 들어있음 (50개)

__listing dict의 key 설명__

- badges: ?
- bathroom_label, bathrooms: 화장실 수
- bed_label, bedroom_label, bedrooms: 침대 수, 침실 형태, 침실 수
- city: 표기 혼재 ex) '서울특별시', '마포구', 'Mapo-gu'
- guest_label: 수용인원?
- host_languages: 호스트 가능 언어
- host_thumbnail_url_small, host_thumbnail_url: 호스트 썸네일
- __id : 숙소 id__ 인듯?
- is_business_travel_ready: 비즈니스 트래블위한 숙소인지
- is_fully_refundable: 환불가능여부
- is_host_highly_rated: 호스트 신뢰가능 여부

... : 기타 features 생략

- kicker_content: 숙소형태 요약?
- lat, lng: 위도 경도
- localized_city: 군,구 수준 주소?
- localized_neighborhood: 지하철역 수준 주소?
- name: 숙소이름
- neighborhood: 근처 뭐있는지?
- person_capacity: 수용가능인원 (guest_label과 차이는뭐지??)
- picture_count,picture_url,picture_urls,picture: 숙소 사진 관련
- preview_amenities: 프리뷰에 보여지는 amenities들인듯 ex) 와이파이, 주방
- property_type_id: room_and_property_type 관련 id인듯
- __reviews_count: 리뷰수__
- room_type_category, room_type: 숙소형태 ex)Entire home/apt

... 기타

- star_rating: 숙소 별점
- tier_id: ?
- __user: 호스트 관련 정보(id, 썸네일..)__
- public_address: 군,구 수준까지 주소
- seo_reviews: ?
- amenity_ids, preview_amenity_names: 보유한 amenity들??
- reviews: ??

In [11]:
# listing의 키밸류 쌍을 뽑아보자
for k,v in res_jsn['explore_tabs'][0]['sections'][1]['listings'][10]['listing'].items():
     print("|| %30s || : %s" % (k,v)) # (|| key || : value) 형태로 출력

||                         badges || : []
||                 bathroom_label || : 1 bath
||                      bathrooms || : 1.0
||                      bed_label || : 2 beds
||                  bedroom_label || : 2 bedrooms
||                       bedrooms || : 2
||                           beds || : 2
||                           city || : Yongsan-gu
||                    guest_label || : 4 guests
||                 host_languages || : ['en', 'ko']
||       host_thumbnail_url_small || : https://a0.muscache.com/im/pictures/970eb53a-a8bd-4a04-a6dc-861846582771.jpg?aki_policy=profile_small
||             host_thumbnail_url || : https://a0.muscache.com/im/pictures/970eb53a-a8bd-4a04-a6dc-861846582771.jpg?aki_policy=profile_x_medium
||                             id || : 16683321
||       is_business_travel_ready || : False
||            is_fully_refundable || : True
||           is_host_highly_rated || : True
||                 is_new_listing || : False
||                  is_rebookable || : False
||                   is_superhost || : True
||                 kicker_content || : {'messages': ['Entire apartment', '2 beds']}
||                            lat || : 37.5546721332994
||                            lng || : 126.96999096640928
||                 localized_city || : Yongsan-gu
||         localized_neighborhood || : Namdaemun
||                           name || : [Seoul station] Cosy house
||                   neighborhood || : Namdaemun
||                person_capacity || : 4
||                  picture_count || : 33
||                    picture_url || : https://a0.muscache.com/im/pictures/7be66c81-1f7a-4337-9582-cb714087dde2.jpg?aki_policy=large
||                   picture_urls || : ['https://a0.muscache.com/im/pictures/7be66c81-1f7a-4337-9582-cb714087dde2.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/c3229d66-039e-46d8-879e-b9b31da780c4.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/d858fb1a-beaf-4e36-a807-164eed8540b4.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/7c17e5ff-28b0-4307-aca8-ccd9eac49810.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/725da0a8-2722-40e1-8b8e-28f62e407d33.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/fef49721-ad6f-4099-82a1-68369bad10ca.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/690bc00c-af1e-4fb6-b450-5ef301fde0a4.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/34c9c7a2-32bf-45d7-94ed-f2f5c3951e2d.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/de5b34b7-722c-43b0-9808-d2c282e4770e.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/824564d6-acc1-4826-b3ad-bca428351842.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/33b4d148-5d7e-4420-8f4e-33c76b4d7def.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/2f7d187a-5067-490d-aee7-e957b6a7a146.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/a1cc4c34-eefd-4d6d-9f39-48da85d5cdab.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/32f33e66-fdcf-4868-98ac-8f34cbb964b8.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/6f1f7cf7-e4aa-4722-a4be-de5e7ac6a429.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/1d6e1b1f-ea93-4e29-8180-d60af7ff69b9.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/3a50276d-fe50-494b-85b0-3b9261f5cdf9.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/8bc66c68-f2e4-4d9c-b9d2-dcd1d1fc317e.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/19223aaf-f148-4657-8f0d-f89a50839722.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/7cc44275-0d7b-429b-afbc-749d734e7191.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/3388f945-43df-4a97-bdd9-b63e01ae407a.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/e67d6cd3-55de-49f6-906b-000bafd672ce.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/3190b4f6-5f68-4a22-b7dd-4d2ef02e04c7.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/24b9ac37-bddc-4caf-b60a-2462a4d52828.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/7ef5b888-74b7-4958-a38b-c756c2ab1827.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/746bf32f-6f95-4a6c-a4d1-3cf3267be756.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/41cfa027-8e39-4042-81fb-69e973f77949.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/6ba20503-d6cb-4a08-bb4b-4603ad413ebd.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/77ae1e2d-c5fa-4ccb-8d78-d761a98c5bc0.jpg?aki_policy=large', 'https://a0.muscache.com/im/pictures/2b0e1a08-4a22-4ab5-9eb7-f62c6f8cb39c.jpg?aki_policy=large']
||                        picture || : {'id': 252095023, 'dominant_saturated_color': '#787878', 'large_ro': 'https://a0.muscache.com/im/pictures/7be66c81-1f7a-4337-9582-cb714087dde2.jpg?aki_policy=large_ro', 'picture': 'https://a0.muscache.com/im/pictures/7be66c81-1f7a-4337-9582-cb714087dde2.jpg?aki_policy=large', 'preview_encoded_png': 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//ASIeGHRoUlpALwofOMO+xwHfsnoJGSXt6voWLkjKvbUBtY1hFRIPo7LaKSorA/XsqqcTUSI1U+gAAAAASUVORK5CYII=', 'saturated_a11y_dark_color': '#787878', 'scrim_color': '#0F0C13'}
||              preview_amenities || : Wifi, Kitchen, Washer
||            preview_encoded_png || : iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//ASIeGHRoUlpALwofOMO+xwHfsnoJGSXt6voWLkjKvbUBtY1hFRIPo7LaKSorA/XsqqcTUSI1U+gAAAAASUVORK5CYII=
||               property_type_id || : 1
||                  reviews_count || : 97
||         room_and_property_type || : Entire apartment
||             room_type_category || : entire_home
||                      room_type || : Entire home/apt
||                    scrim_color || : #0F0C13
||           show_structured_name || : False
||                     space_type || : Entire apartment
||                    star_rating || : 5.0
||                        tier_id || : 0
||                           user || : {'first_name': ' ', 'has_profile_pic': True, 'id': 110426916, 'is_superhost': True, 'picture_url': 'https://a0.muscache.com/im/pictures/970eb53a-a8bd-4a04-a6dc-861846582771.jpg?aki_policy=profile_x_medium', 'smart_name': ' ', 'thumbnail_url': 'https://a0.muscache.com/im/pictures/970eb53a-a8bd-4a04-a6dc-861846582771.jpg?aki_policy=profile_small'}
||            wide_kicker_content || : {'messages': ['Entire apartment']}
||                 public_address || : Yongsan-gu, Seoul, South Korea
||                    seo_reviews || : []
||                    amenity_ids || : [1, 2, 3, 4, 5, 8, 14, 21, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 57]
||          preview_amenity_names || : ['Wifi', 'Kitchen', 'Washer']
||                        reviews || : []

In [12]:
res_jsn['explore_tabs'][0]['experiments_metadata'] # 뭐없다

[]

home_tab에 대한 메타데이터도 뽑아보자

결과적으로 여기의 remarketing_ids 에서 숙소 id를 바로 뽑는다

In [13]:
for k,v in res_jsn['explore_tabs'][0]['home_tab_metadata'].items():
    if k == 'filters': continue # filters 너무 많아 출력 안하겠다
    print("|| %30s || : %s" % (k,v)) # (|| key || : value) 형태로 출력

||             urgency_commitment || : {'message_type': 'empty_message', 'message': {}}
|| golden_ticket_urgency_commitment || : {'message_type': 'empty_message', 'message': {}}
|| listing_cards_urgency_commitment_metadata || : []
|| listing_cards_price_line_urgency_commitment_metadata || : []
||                       messages || : {}
||                         facets || : {}
||                      overrides || : {}
||              search_feed_items || : []
||                remarketing_ids || : [8213750, 11444903, 18956008, 12778317, 22320269, 4619104, 19777144, 17560209, 16683321, 16965764, 22133272, 18739581, 18967029, 20719576, 19634147, 20129439, 1753246, 17578320, 10044927, 21007367, 12857880, 14440359, 20763289, 15596154, 18385571, 4258317, 14069246, 19378056, 17481718, 15649684, 9710807, 8996724, 22056285, 20292369, 19576908, 18473432, 1077893, 16013768, 17660903, 14885947, 11802302, 5714483, 19433253, 10127540, 9715695, 7128212, 1634115, 982772, 24129062, 14482939, 20546115, 18166957, 825230, 19778279, 9663158, 18675619, 13921817, 8777431, 21705098, 14976052, 25764855, 18562564, 10969312, 14578227, 21742234, 18641438, 17482061, 21959899, 23722060, 14951883, 15429401, 16305610, 20184364, 8108953, 22241038, 21901887, 18793625, 19678445, 19564652, 18501662, 17215696, 21920181, 8139172, 1755951, 18277895, 1764218, 15089817, 15306314, 12142413, 17370939, 16589888, 19772800, 11573127, 16139057, 21329957, 13775341, 16007254, 20426343, 26262255, 19227515]
||                       location || : {'canonical_location': 'Seoul, South Korea', 'display_location': 'Seoul'}
||                    breadcrumbs || : [{'location_name': 'South Korea', 'canonical_location_name': 'South Korea', 'type': 'country'}, {'location_name': 'Seoul', 'canonical_location_name': 'Seoul, South Korea', 'type': 'state'}, {'location_name': 'Seoul', 'canonical_location_name': 'Seoul, South Korea', 'type': 'city'}]
||                 listings_count || : 1001
||                         search || : {'native_currency': 'KRW', 'price_range_max_native': 1000000, 'price_range_min_native': 11000, 'price_type': 'nightly', 'search_id': '46d3efc5-f986-4b8b-b315-af3a94680376', 'mobile_session_id': 'fAJQlQyk', 'is_business_travel_verified': False, 'business_travel_ready_data': {'filter_criteria': {}, 'show_btr_upsell': False}}
||                      geography || : {'accuracy': 4, 'city': 'Seoul', 'country_code': 'KR', 'country': 'South Korea', 'lat': 37.566535, 'lng': 126.9779692, 'place_id': 'ChIJzWXFYYuifDUR64Pq5LTtioU', 'precision': 'city', 'result_type': 'locality', 'state': 'Seoul', 'state_short': 'Seoul', 'extended_precision': 'city'}
||                price_histogram || : {'average_price': 57283, 'histogram': [150, 127, 307, 233, 681, 875, 1245, 1140, 1509, 2008, 1322, 1670, 1180, 910, 791, 353, 287, 211, 251, 134, 113, 161, 45, 59, 83, 31, 41, 59, 33, 30, 28, 10, 3, 14, 7, 22, 8, 11, 5, 2, 6, 8, 1, 1, 3, 0, 0, 1, 1, 30]}

In [14]:
# res_jsn['explore_tabs'][0]['home_tab_metadata']['filters'] # 필터 정보 들여다볼 필요있으면 켜보자

In [15]:
res_jsn['metadata'] # 마지막으로 res_json 전체에 대한 metadata이다 어떻게 고쳐야할지...

{'current_tab_id': 'home_tab',
 'request_uuid': '44734ba5-83ed-4b45-8575-dca541f1e5ee',
 'search_id': '44734ba5-83ed-4b45-8575-dca541f1e5ee',
 'query': '서울',
 'query_text': '서울특별시 · Homes',
 'current_refinement_paths': ['/homes'],
 'federated_search_id': '7ac2d6a3-e859-4cf1-aa51-1fe67d422f33',
 'federated_search_session_id': '1952caa0-a801-44bb-a9e7-cb7aabcaff7c',
 'suggestions': [{'title': 'All',
   'type': 'for_you',
   'search_params': {'params': [],
    'query': '서울',
    'refinement_paths': ['/for_you'],
    'refinement_path': '/for_you',
    'tab_id': 'all_tab'},
   'is_selected': False},
  {'title': 'Homes',
   'type': 'homes',
   'search_params': {'params': [],
    'query': '서울',
    'refinement_paths': ['/homes'],
    'refinement_path': '/homes',
    'tab_id': 'home_tab'},
   'is_selected': True},
  {'title': 'Experiences',
   'type': 'experiences',
   'search_params': {'params': [],
    'query': '서울',
    'refinement_paths': ['/experiences'],
    'refinement_path': '/experiences',
    'tab_id': 'experience_tab'},
   'is_selected': False}],
 'has_map': True,
 'show_as_hint': False,
 'marquee_mode': 'DEFAULT',
 'satori_version': '1.0.3',
 'gtm_experiments': [],
 'saved_search_responses': [],
 'map_toggle': False,
 'price_display_strategy': 'CONTROL',
 'satori_config': {'market': 'Seoul',
  'state_code': '',
  'country_code': 'KR',
  'region_id': -1,
  'version': '1.1.0'},
 'page_metadata': {'page_title': '서울특별시 · Homes · Airbnb',
  'render_type': 'EXPLORE'}}

In [43]:
url = "https://api.airbnb.com/v2/explore_tabs"
params = {
    'key':'d306zoyjsyarp7ifhu67rjxn52tv0t20',
    '_format':'for_explore_search_web',
    
    'currency':'KRW',
    'location':'서울',
    'tab_id':'home_tab',
    'items_per_grid':'500', # 최대 306 -> 수정할방법찾아야
#     'section_offset':'1',
#     'supports_for_you_v3':'true',
    'timezone_offset':'300',
    'version':'1.3.9',
    'price_min':'0',
    'price_max':'99',
    }
headers = {'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}

In [44]:
%%time
home = {}
while int(params['price_max']) < 1000000:
    print(params['price_min'],params['price_max'])
    
    retry = 3 # request 예외발생시 재시도 횟수
    while retry !=0:
        try:
            resp = requests.get(url,params=params)
            res_jsn = resp.json()
            home_count = len(res_jsn['explore_tabs'][0]['sections'][1]['listings'])
            break

        except Exception as e:
            retry -= 1
            print('ERR: btw {} and {}'.format(params['price_min'],params['price_max']),end='|')
            print(e)
            time.sleep(1)
            continue
    
    if retry ==0:
        print('해당 데이터 못가져옴')
        continue
    if home_count > 0:
        print('해당가격대 숙소 count: ',home_count)
        for el in res_jsn['explore_tabs'][0]['sections'][1]['listings']:
            tmp_dict = el['listing']
            tmp_id = str(tmp_dict['id'])
#             if home.get(tmp_id) is not None: print('home_id {} is overlapped, be updated'.format(tmp_id))
            del tmp_dict['id']
            home[tmp_id] = tmp_dict
    
    if int(params['price_max']) < 100000: # 십만원 기준으로 그미만은 100원단위, 이상은 1000원 단위로 request
        params['price_min'] = str(int(params['price_min']) + 100) # 가격필터 변경(100원단위)
        params['price_max'] = str(int(params['price_min']) + 99)
    else:
        params['price_min'] = str(int(params['price_min']) + 1000) # 가격필터 변경(1000원단위)
        params['price_max'] = str(int(params['price_min']) + 999)

0 99
100 199
ERR: btw 100 and 199|'explore_tabs'
200 299
300 399
ERR: btw 300 and 399|Expecting value: line 1 column 1 (char 0)
400 499
500 599
600 699
700 799
800 899
900 999
1000 1099
1100 1199
1200 1299
1300 1399
ERR: btw 1300 and 1399|'explore_tabs'
1400 1499
1500 1599
1600 1699
ERR: btw 1600 and 1699|Expecting value: line 1 column 1 (char 0)
1700 1799
1800 1899
ERR: btw 1800 and 1899|Expecting value: line 1 column 1 (char 0)
ERR: btw 1800 and 1899|Expecting value: line 1 column 1 (char 0)
1900 1999
ERR: btw 1900 and 1999|Expecting value: line 1 column 1 (char 0)
2000 2099
ERR: btw 2000 and 2099|'explore_tabs'
2100 2199
2200 2299
ERR: btw 2200 and 2299|Expecting value: line 1 column 1 (char 0)
2300 2399
ERR: btw 2300 and 2399|'explore_tabs'
2400 2499
2500 2599
2600 2699
2700 2799
ERR: btw 2700 and 2799|'explore_tabs'
2800 2899
2900 2999
3000 3099
3100 3199
ERR: btw 3100 and 3199|'explore_tabs'
3200 3299
3300 3399
3400 3499
ERR: btw 3400 and 3499|'explore_tabs'
3500 3599
ERR: btw 3500 and 3599|'explore_tabs'
ERR: btw 3500 and 3599|'explore_tabs'
3600 3699
3700 3799
3800 3899
3900 3999
4000 4099
4100 4199
ERR: btw 4100 and 4199|'explore_tabs'
ERR: btw 4100 and 4199|Expecting value: line 1 column 1 (char 0)
ERR: btw 4100 and 4199|'explore_tabs'
해당 데이터 못가져옴
4100 4199
ERR: btw 4100 and 4199|'explore_tabs'
ERR: btw 4100 and 4199|'explore_tabs'
4200 4299
4300 4399
4400 4499
4500 4599
ERR: btw 4500 and 4599|'explore_tabs'
4600 4699
4700 4799
4800 4899
ERR: btw 4800 and 4899|Expecting value: line 1 column 1 (char 0)
4900 4999
5000 5099
해당가격대 숙소 count:  1
5100 5199
해당가격대 숙소 count:  1
5200 5299
ERR: btw 5200 and 5299|'explore_tabs'
해당가격대 숙소 count:  1
5300 5399
해당가격대 숙소 count:  1
5400 5499
ERR: btw 5400 and 5499|'explore_tabs'
ERR: btw 5400 and 5499|'explore_tabs'
해당가격대 숙소 count:  1
5500 5599
해당가격대 숙소 count:  1
5600 5699
해당가격대 숙소 count:  1
5700 5799
해당가격대 숙소 count:  1
5800 5899
해당가격대 숙소 count:  1
5900 5999
해당가격대 숙소 count:  1
6000 6099
해당가격대 숙소 count:  1
6100 6199
해당가격대 숙소 count:  2
6200 6299
ERR: btw 6200 and 6299|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  1
6300 6399
해당가격대 숙소 count:  1
6400 6499
ERR: btw 6400 and 6499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  1
6500 6599
해당가격대 숙소 count:  1
6600 6699
ERR: btw 6600 and 6699|'explore_tabs'
해당가격대 숙소 count:  1
6700 6799
해당가격대 숙소 count:  1
6800 6899
ERR: btw 6800 and 6899|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  1
6900 6999
해당가격대 숙소 count:  1
7000 7099
해당가격대 숙소 count:  1
7100 7199
해당가격대 숙소 count:  1
7200 7299
ERR: btw 7200 and 7299|'explore_tabs'
해당가격대 숙소 count:  2
7300 7399
해당가격대 숙소 count:  1
7400 7499
해당가격대 숙소 count:  1
7500 7599
해당가격대 숙소 count:  1
7600 7699
해당가격대 숙소 count:  1
7700 7799
해당가격대 숙소 count:  1
7800 7899
해당가격대 숙소 count:  1
7900 7999
해당가격대 숙소 count:  1
8000 8099
해당가격대 숙소 count:  1
8100 8199
해당가격대 숙소 count:  1
8200 8299
해당가격대 숙소 count:  1
8300 8399
해당가격대 숙소 count:  1
8400 8499
해당가격대 숙소 count:  1
8500 8599
8600 8699
8700 8799
8800 8899
8900 8999
9000 9099
ERR: btw 9000 and 9099|'explore_tabs'
ERR: btw 9000 and 9099|Expecting value: line 1 column 1 (char 0)
ERR: btw 9000 and 9099|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
9000 9099
ERR: btw 9000 and 9099|'explore_tabs'
9100 9199
9200 9299
9300 9399
9400 9499
9500 9599
해당가격대 숙소 count:  4
9600 9699
해당가격대 숙소 count:  4
9700 9799
ERR: btw 9700 and 9799|'explore_tabs'
ERR: btw 9700 and 9799|'explore_tabs'
해당가격대 숙소 count:  4
9800 9899
해당가격대 숙소 count:  4
9900 9999
해당가격대 숙소 count:  4
10000 10099
해당가격대 숙소 count:  4
10100 10199
해당가격대 숙소 count:  4
10200 10299
해당가격대 숙소 count:  4
10300 10399
해당가격대 숙소 count:  4
10400 10499
해당가격대 숙소 count:  4
10500 10599
ERR: btw 10500 and 10599|'explore_tabs'
ERR: btw 10500 and 10599|'explore_tabs'
ERR: btw 10500 and 10599|'explore_tabs'
해당 데이터 못가져옴
10500 10599
해당가격대 숙소 count:  4
10600 10699
해당가격대 숙소 count:  163
10700 10799
해당가격대 숙소 count:  159
10800 10899
해당가격대 숙소 count:  159
10900 10999
해당가격대 숙소 count:  159
11000 11099
해당가격대 숙소 count:  159
11100 11199
해당가격대 숙소 count:  159
11200 11299
해당가격대 숙소 count:  159
11300 11399
ERR: btw 11300 and 11399|'explore_tabs'
해당가격대 숙소 count:  159
11400 11499
ERR: btw 11400 and 11499|Expecting value: line 1 column 1 (char 0)
ERR: btw 11400 and 11499|'explore_tabs'
해당가격대 숙소 count:  159
11500 11599
해당가격대 숙소 count:  159
11600 11699
해당가격대 숙소 count:  159
11700 11799
해당가격대 숙소 count:  280
11800 11899
해당가격대 숙소 count:  121
11900 11999
해당가격대 숙소 count:  121
12000 12099
해당가격대 숙소 count:  121
12100 12199
해당가격대 숙소 count:  121
12200 12299
해당가격대 숙소 count:  121
12300 12399
해당가격대 숙소 count:  121
12400 12499
해당가격대 숙소 count:  121
12500 12599
해당가격대 숙소 count:  121
12600 12699
해당가격대 숙소 count:  121
12700 12799
ERR: btw 12700 and 12799|'explore_tabs'
해당가격대 숙소 count:  121
12800 12899
ERR: btw 12800 and 12899|'explore_tabs'
해당가격대 숙소 count:  121
12900 12999
해당가격대 숙소 count:  237
13000 13099
ERR: btw 13000 and 13099|'explore_tabs'
해당가격대 숙소 count:  116
13100 13199
해당가격대 숙소 count:  116
13200 13299
해당가격대 숙소 count:  116
13300 13399
해당가격대 숙소 count:  116
13400 13499
해당가격대 숙소 count:  116
13500 13599
해당가격대 숙소 count:  116
13600 13699
ERR: btw 13600 and 13699|'explore_tabs'
해당가격대 숙소 count:  116
13700 13799
해당가격대 숙소 count:  116
13800 13899
해당가격대 숙소 count:  116
13900 13999
ERR: btw 13900 and 13999|'explore_tabs'
해당가격대 숙소 count:  116
14000 14099
ERR: btw 14000 and 14099|'explore_tabs'
해당가격대 숙소 count:  289
14100 14199
ERR: btw 14100 and 14199|Expecting value: line 1 column 1 (char 0)
ERR: btw 14100 and 14199|'explore_tabs'
해당가격대 숙소 count:  173
14200 14299
해당가격대 숙소 count:  173
14300 14399
해당가격대 숙소 count:  173
14400 14499
해당가격대 숙소 count:  173
14500 14599
ERR: btw 14500 and 14599|'explore_tabs'
해당가격대 숙소 count:  173
14600 14699
해당가격대 숙소 count:  173
14700 14799
ERR: btw 14700 and 14799|'explore_tabs'
해당가격대 숙소 count:  173
14800 14899
해당가격대 숙소 count:  173
14900 14999
해당가격대 숙소 count:  173
15000 15099
해당가격대 숙소 count:  173
15100 15199
해당가격대 숙소 count:  293
15200 15299
해당가격대 숙소 count:  120
15300 15399
해당가격대 숙소 count:  120
15400 15499
해당가격대 숙소 count:  120
15500 15599
해당가격대 숙소 count:  120
15600 15699
ERR: btw 15600 and 15699|'explore_tabs'
ERR: btw 15600 and 15699|'explore_tabs'
ERR: btw 15600 and 15699|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
15600 15699
ERR: btw 15600 and 15699|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  120
15700 15799
해당가격대 숙소 count:  120
15800 15899
해당가격대 숙소 count:  120
15900 15999
해당가격대 숙소 count:  120
16000 16099
해당가격대 숙소 count:  120
16100 16199
ERR: btw 16100 and 16199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  120
16200 16299
ERR: btw 16200 and 16299|'explore_tabs'
해당가격대 숙소 count:  241
16300 16399
해당가격대 숙소 count:  121
16400 16499
해당가격대 숙소 count:  121
16500 16599
해당가격대 숙소 count:  121
16600 16699
해당가격대 숙소 count:  121
16700 16799
해당가격대 숙소 count:  121
16800 16899
ERR: btw 16800 and 16899|'explore_tabs'
해당가격대 숙소 count:  121
16900 16999
해당가격대 숙소 count:  121
17000 17099
해당가격대 숙소 count:  121
17100 17199
ERR: btw 17100 and 17199|'explore_tabs'
해당가격대 숙소 count:  121
17200 17299
해당가격대 숙소 count:  121
17300 17399
해당가격대 숙소 count:  306
17400 17499
ERR: btw 17400 and 17499|'explore_tabs'
해당가격대 숙소 count:  204
17500 17599
ERR: btw 17500 and 17599|'explore_tabs'
해당가격대 숙소 count:  204
17600 17699
해당가격대 숙소 count:  204
17700 17799
해당가격대 숙소 count:  204
17800 17899
해당가격대 숙소 count:  204
17900 17999
해당가격대 숙소 count:  204
18000 18099
해당가격대 숙소 count:  204
18100 18199
해당가격대 숙소 count:  204
18200 18299
ERR: btw 18200 and 18299|'explore_tabs'
해당가격대 숙소 count:  204
18300 18399
해당가격대 숙소 count:  204
18400 18499
해당가격대 숙소 count:  204
18500 18599
해당가격대 숙소 count:  306
18600 18699
해당가격대 숙소 count:  129
18700 18799
ERR: btw 18700 and 18799|'explore_tabs'
해당가격대 숙소 count:  129
18800 18899
해당가격대 숙소 count:  129
18900 18999
해당가격대 숙소 count:  129
19000 19099
ERR: btw 19000 and 19099|'explore_tabs'
해당가격대 숙소 count:  129
19100 19199
해당가격대 숙소 count:  129
19200 19299
해당가격대 숙소 count:  129
19300 19399
해당가격대 숙소 count:  129
19400 19499
해당가격대 숙소 count:  129
19500 19599
해당가격대 숙소 count:  129
19600 19699
해당가격대 숙소 count:  306
19700 19799
해당가격대 숙소 count:  306
19800 19899
해당가격대 숙소 count:  306
19900 19999
해당가격대 숙소 count:  306
20000 20099
해당가격대 숙소 count:  306
20100 20199
해당가격대 숙소 count:  306
20200 20299

ERR: btw 20200 and 20299|'explore_tabs'
해당가격대 숙소 count:  306
20300 20399
해당가격대 숙소 count:  306
20400 20499
해당가격대 숙소 count:  306
20500 20599
해당가격대 숙소 count:  306
20600 20699
해당가격대 숙소 count:  306
20700 20799
해당가격대 숙소 count:  306
20800 20899
해당가격대 숙소 count:  121
20900 20999
해당가격대 숙소 count:  121
21000 21099
해당가격대 숙소 count:  121
21100 21199
해당가격대 숙소 count:  121
21200 21299
해당가격대 숙소 count:  121
21300 21399
ERR: btw 21300 and 21399|'explore_tabs'
해당가격대 숙소 count:  121
21400 21499
해당가격대 숙소 count:  121
21500 21599
해당가격대 숙소 count:  121
21600 21699
해당가격대 숙소 count:  121
21700 21799
해당가격대 숙소 count:  121
21800 21899
해당가격대 숙소 count:  306
21900 21999
ERR: btw 21900 and 21999|'explore_tabs'
해당가격대 숙소 count:  248
22000 22099
해당가격대 숙소 count:  248
22100 22199
해당가격대 숙소 count:  248
22200 22299
해당가격대 숙소 count:  248
22300 22399
해당가격대 숙소 count:  248
22400 22499
해당가격대 숙소 count:  248
22500 22599
해당가격대 숙소 count:  248
22600 22699
해당가격대 숙소 count:  248
22700 22799
해당가격대 숙소 count:  248
22800 22899
해당가격대 숙소 count:  248
22900 22999
해당가격대 숙소 count:  248
23000 23099
해당가격대 숙소 count:  306
23100 23199
해당가격대 숙소 count:  116
23200 23299
해당가격대 숙소 count:  116
23300 23399
해당가격대 숙소 count:  116
23400 23499
해당가격대 숙소 count:  116
23500 23599
해당가격대 숙소 count:  116
23600 23699
해당가격대 숙소 count:  116
23700 23799
해당가격대 숙소 count:  116
23800 23899
해당가격대 숙소 count:  116
23900 23999
해당가격대 숙소 count:  116
24000 24099
해당가격대 숙소 count:  116
24100 24199
해당가격대 숙소 count:  306
24200 24299
ERR: btw 24200 and 24299|'explore_tabs'
해당가격대 숙소 count:  306
24300 24399
해당가격대 숙소 count:  306
24400 24499
해당가격대 숙소 count:  306
24500 24599
해당가격대 숙소 count:  306
24600 24699
해당가격대 숙소 count:  306
24700 24799
해당가격대 숙소 count:  306
24800 24899
해당가격대 숙소 count:  306
24900 24999
ERR: btw 24900 and 24999|'explore_tabs'
해당가격대 숙소 count:  306
25000 25099
해당가격대 숙소 count:  306
25100 25199
해당가격대 숙소 count:  306
25200 25299
해당가격대 숙소 count:  306
25300 25399
해당가격대 숙소 count:  137
25400 25499
해당가격대 숙소 count:  137
25500 25599
해당가격대 숙소 count:  137
25600 25699
해당가격대 숙소 count:  137
25700 25799
해당가격대 숙소 count:  137
25800 25899
해당가격대 숙소 count:  137
25900 25999
해당가격대 숙소 count:  137
26000 26099
해당가격대 숙소 count:  137
26100 26199
해당가격대 숙소 count:  137
26200 26299
해당가격대 숙소 count:  137
26300 26399
해당가격대 숙소 count:  283
26400 26499
해당가격대 숙소 count:  146
26500 26599
해당가격대 숙소 count:  146
26600 26699
해당가격대 숙소 count:  146
26700 26799
해당가격대 숙소 count:  146
26800 26899
해당가격대 숙소 count:  146
26900 26999
해당가격대 숙소 count:  146
27000 27099
해당가격대 숙소 count:  146
27100 27199
해당가격대 숙소 count:  146
27200 27299
해당가격대 숙소 count:  146
27300 27399
해당가격대 숙소 count:  146
27400 27499
해당가격대 숙소 count:  306
27500 27599
해당가격대 숙소 count:  253
27600 27699
해당가격대 숙소 count:  253
27700 27799
해당가격대 숙소 count:  253
27800 27899
해당가격대 숙소 count:  253
27900 27999
해당가격대 숙소 count:  253
28000 28099
해당가격대 숙소 count:  253
28100 28199
해당가격대 숙소 count:  253
28200 28299
해당가격대 숙소 count:  253
28300 28399
해당가격대 숙소 count:  253
28400 28499
해당가격대 숙소 count:  253
28500 28599
해당가격대 숙소 count:  253
28600 28699
해당가격대 숙소 count:  306
28700 28799
해당가격대 숙소 count:  205
28800 28899
해당가격대 숙소 count:  205
28900 28999
해당가격대 숙소 count:  205
29000 29099
해당가격대 숙소 count:  205
29100 29199
해당가격대 숙소 count:  205
29200 29299
해당가격대 숙소 count:  205
29300 29399
해당가격대 숙소 count:  205
29400 29499
해당가격대 숙소 count:  205
29500 29599
해당가격대 숙소 count:  205
29600 29699
해당가격대 숙소 count:  205
29700 29799
해당가격대 숙소 count:  306
29800 29899
해당가격대 숙소 count:  306
29900 29999
해당가격대 숙소 count:  306
30000 30099
해당가격대 숙소 count:  306
30100 30199
해당가격대 숙소 count:  306
30200 30299
해당가격대 숙소 count:  306
30300 30399
해당가격대 숙소 count:  306
30400 30499
해당가격대 숙소 count:  306
30500 30599
해당가격대 숙소 count:  306
30600 30699
해당가격대 숙소 count:  306
30700 30799
해당가격대 숙소 count:  306
30800 30899
해당가격대 숙소 count:  306
30900 30999
해당가격대 숙소 count:  129
31000 31099
해당가격대 숙소 count:  129
31100 31199
해당가격대 숙소 count:  129
31200 31299
해당가격대 숙소 count:  129
31300 31399
해당가격대 숙소 count:  129
31400 31499
해당가격대 숙소 count:  129
31500 31599
해당가격대 숙소 count:  129
31600 31699
해당가격대 숙소 count:  129
31700 31799
해당가격대 숙소 count:  129
31800 31899
해당가격대 숙소 count:  129
31900 31999
해당가격대 숙소 count:  306
32000 32099
해당가격대 숙소 count:  244
32100 32199
해당가격대 숙소 count:  244
32200 32299
해당가격대 숙소 count:  244
32300 32399
해당가격대 숙소 count:  244
32400 32499
해당가격대 숙소 count:  244
32500 32599
해당가격대 숙소 count:  244
32600 32699
해당가격대 숙소 count:  244
32700 32799
해당가격대 숙소 count:  244
32800 32899
해당가격대 숙소 count:  244
32900 32999
해당가격대 숙소 count:  244
33000 33099
해당가격대 숙소 count:  244
33100 33199
해당가격대 숙소 count:  306
33200 33299
해당가격대 숙소 count:  216
33300 33399
해당가격대 숙소 count:  216
33400 33499
해당가격대 숙소 count:  216
33500 33599
해당가격대 숙소 count:  216
33600 33699
해당가격대 숙소 count:  216
33700 33799
해당가격대 숙소 count:  216
33800 33899
해당가격대 숙소 count:  216
33900 33999
해당가격대 숙소 count:  216
34000 34099
해당가격대 숙소 count:  216
34100 34199
해당가격대 숙소 count:  216
34200 34299
해당가격대 숙소 count:  306
34300 34399
해당가격대 숙소 count:  306
34400 34499
해당가격대 숙소 count:  306
34500 34599
해당가격대 숙소 count:  306
34600 34699
해당가격대 숙소 count:  306
34700 34799
ERR: btw 34700 and 34799|'explore_tabs'
해당가격대 숙소 count:  306
34800 34899
해당가격대 숙소 count:  306
34900 34999
해당가격대 숙소 count:  306
35000 35099
해당가격대 숙소 count:  306
35100 35199
해당가격대 숙소 count:  306
35200 35299
해당가격대 숙소 count:  306
35300 35399
해당가격대 숙소 count:  306
35400 35499
해당가격대 숙소 count:  180
35500 35599
해당가격대 숙소 count:  180
35600 35699
해당가격대 숙소 count:  180
35700 35799
해당가격대 숙소 count:  180
35800 35899
해당가격대 숙소 count:  180
35900 35999
해당가격대 숙소 count:  180
36000 36099
해당가격대 숙소 count:  180
36100 36199
해당가격대 숙소 count:  180
36200 36299
해당가격대 숙소 count:  180
36300 36399
해당가격대 숙소 count:  180
36400 36499
해당가격대 숙소 count:  303
36500 36599
해당가격대 숙소 count:  123
36600 36699
해당가격대 숙소 count:  123
36700 36799
해당가격대 숙소 count:  123
36800 36899
해당가격대 숙소 count:  123
36900 36999
해당가격대 숙소 count:  123
37000 37099
해당가격대 숙소 count:  123
37100 37199
해당가격대 숙소 count:  123
37200 37299
해당가격대 숙소 count:  123
37300 37399
해당가격대 숙소 count:  123
37400 37499
해당가격대 숙소 count:  123
37500 37599
해당가격대 숙소 count:  299
37600 37699
해당가격대 숙소 count:  176
37700 37799
해당가격대 숙소 count:  176
37800 37899
해당가격대 숙소 count:  176
37900 37999
해당가격대 숙소 count:  176
38000 38099
해당가격대 숙소 count:  176
38100 38199
해당가격대 숙소 count:  176
38200 38299
해당가격대 숙소 count:  176
38300 38399
해당가격대 숙소 count:  176
38400 38499
해당가격대 숙소 count:  176
38500 38599
해당가격대 숙소 count:  176
38600 38699
해당가격대 숙소 count:  176
38700 38799
해당가격대 숙소 count:  306
38800 38899
해당가격대 숙소 count:  252
38900 38999
해당가격대 숙소 count:  252
39000 39099
해당가격대 숙소 count:  252
39100 39199
해당가격대 숙소 count:  252
39200 39299
해당가격대 숙소 count:  252
39300 39399
해당가격대 숙소 count:  252
39400 39499
해당가격대 숙소 count:  252
39500 39599
해당가격대 숙소 count:  252
39600 39699
해당가격대 숙소 count:  252
39700 39799
해당가격대 숙소 count:  252
39800 39899
해당가격대 숙소 count:  306
39900 39999
해당가격대 숙소 count:  306
40000 40099
해당가격대 숙소 count:  306
40100 40199
해당가격대 숙소 count:  306
40200 40299
해당가격대 숙소 count:  306
40300 40399
해당가격대 숙소 count:  306
40400 40499
해당가격대 숙소 count:  306
40500 40599
해당가격대 숙소 count:  306
40600 40699
해당가격대 숙소 count:  306
40700 40799
해당가격대 숙소 count:  306
40800 40899
해당가격대 숙소 count:  306
40900 40999
해당가격대 숙소 count:  306
41000 41099
해당가격대 숙소 count:  253
41100 41199
해당가격대 숙소 count:  253
41200 41299
해당가격대 숙소 count:  253
41300 41399
해당가격대 숙소 count:  253
41400 41499
해당가격대 숙소 count:  253
41500 41599
해당가격대 숙소 count:  253
41600 41699
해당가격대 숙소 count:  253
41700 41799
해당가격대 숙소 count:  253
41800 41899
해당가격대 숙소 count:  253
41900 41999
해당가격대 숙소 count:  253
42000 42099
해당가격대 숙소 count:  306
42100 42199
해당가격대 숙소 count:  166
42200 42299
해당가격대 숙소 count:  166
42300 42399
해당가격대 숙소 count:  166
42400 42499
해당가격대 숙소 count:  166
42500 42599
해당가격대 숙소 count:  166
42600 42699
해당가격대 숙소 count:  166
42700 42799
해당가격대 숙소 count:  166
42800 42899
해당가격대 숙소 count:  166
42900 42999
해당가격대 숙소 count:  166
43000 43099
해당가격대 숙소 count:  166
43100 43199
해당가격대 숙소 count:  166
43200 43299
해당가격대 숙소 count:  150
43300 43399
해당가격대 숙소 count:  150
43400 43499
해당가격대 숙소 count:  150
43500 43599
해당가격대 숙소 count:  150
43600 43699
해당가격대 숙소 count:  150
43700 43799
해당가격대 숙소 count:  150
43800 43899
해당가격대 숙소 count:  150
43900 43999
해당가격대 숙소 count:  150
44000 44099
해당가격대 숙소 count:  150
44100 44199
해당가격대 숙소 count:  150
44200 44299
해당가격대 숙소 count:  150
44300 44399

해당가격대 숙소 count:  306
44400 44499
해당가격대 숙소 count:  306
44500 44599
해당가격대 숙소 count:  306
44600 44699
해당가격대 숙소 count:  306
44700 44799
해당가격대 숙소 count:  306
44800 44899
해당가격대 숙소 count:  306
44900 44999
해당가격대 숙소 count:  306
45000 45099
해당가격대 숙소 count:  306
45100 45199
해당가격대 숙소 count:  306
45200 45299
해당가격대 숙소 count:  306
45300 45399
해당가격대 숙소 count:  306
45400 45499
해당가격대 숙소 count:  306
45500 45599
해당가격대 숙소 count:  104
45600 45699
해당가격대 숙소 count:  104
45700 45799
해당가격대 숙소 count:  104
45800 45899
해당가격대 숙소 count:  104
45900 45999
해당가격대 숙소 count:  104
46000 46099
해당가격대 숙소 count:  104
46100 46199
해당가격대 숙소 count:  104
46200 46299
해당가격대 숙소 count:  104
46300 46399
해당가격대 숙소 count:  104
46400 46499
해당가격대 숙소 count:  104
46500 46599
해당가격대 숙소 count:  254
46600 46699
해당가격대 숙소 count:  150
46700 46799
해당가격대 숙소 count:  150
46800 46899
해당가격대 숙소 count:  150
46900 46999
해당가격대 숙소 count:  150
47000 47099
해당가격대 숙소 count:  150
47100 47199
해당가격대 숙소 count:  150
47200 47299
해당가격대 숙소 count:  150
47300 47399
해당가격대 숙소 count:  150
47400 47499
해당가격대 숙소 count:  150
47500 47599
해당가격대 숙소 count:  150
47600 47699
해당가격대 숙소 count:  306
47700 47799
해당가격대 숙소 count:  202
47800 47899
해당가격대 숙소 count:  202
47900 47999
ERR: btw 47900 and 47999|'explore_tabs'
해당가격대 숙소 count:  202
48000 48099
해당가격대 숙소 count:  202
48100 48199
해당가격대 숙소 count:  202
48200 48299
해당가격대 숙소 count:  202
48300 48399
ERR: btw 48300 and 48399|'explore_tabs'
해당가격대 숙소 count:  202
48400 48499
해당가격대 숙소 count:  202
48500 48599
해당가격대 숙소 count:  202
48600 48699
해당가격대 숙소 count:  202
48700 48799
해당가격대 숙소 count:  202
48800 48899
해당가격대 숙소 count:  306
48900 48999
해당가격대 숙소 count:  187
49000 49099
해당가격대 숙소 count:  187
49100 49199
해당가격대 숙소 count:  187
49200 49299
해당가격대 숙소 count:  187
49300 49399
해당가격대 숙소 count:  187
49400 49499
해당가격대 숙소 count:  187
49500 49599
해당가격대 숙소 count:  187
49600 49699
해당가격대 숙소 count:  187
49700 49799
해당가격대 숙소 count:  187
49800 49899
해당가격대 숙소 count:  187
49900 49999
해당가격대 숙소 count:  306
50000 50099
해당가격대 숙소 count:  306
50100 50199
해당가격대 숙소 count:  306
50200 50299
해당가격대 숙소 count:  306
50300 50399
ERR: btw 50300 and 50399|'explore_tabs'
해당가격대 숙소 count:  306
50400 50499
해당가격대 숙소 count:  306
50500 50599
해당가격대 숙소 count:  306
50600 50699
해당가격대 숙소 count:  306
50700 50799
해당가격대 숙소 count:  306
50800 50899
해당가격대 숙소 count:  306
50900 50999
해당가격대 숙소 count:  306
51000 51099
해당가격대 숙소 count:  306
51100 51199
해당가격대 숙소 count:  116
51200 51299
해당가격대 숙소 count:  116
51300 51399
해당가격대 숙소 count:  116
51400 51499
ERR: btw 51400 and 51499|'explore_tabs'
해당가격대 숙소 count:  116
51500 51599
해당가격대 숙소 count:  116
51600 51699
해당가격대 숙소 count:  116
51700 51799
해당가격대 숙소 count:  116
51800 51899
해당가격대 숙소 count:  116
51900 51999
ERR: btw 51900 and 51999|'explore_tabs'
ERR: btw 51900 and 51999|'explore_tabs'
해당가격대 숙소 count:  116
52000 52099
해당가격대 숙소 count:  116
52100 52199
해당가격대 숙소 count:  227
52200 52299
해당가격대 숙소 count:  111
52300 52399
해당가격대 숙소 count:  111
52400 52499
해당가격대 숙소 count:  111
52500 52599
해당가격대 숙소 count:  111
52600 52699
해당가격대 숙소 count:  111
52700 52799
ERR: btw 52700 and 52799|'explore_tabs'
ERR: btw 52700 and 52799|'explore_tabs'
해당가격대 숙소 count:  111
52800 52899
해당가격대 숙소 count:  111
52900 52999
ERR: btw 52900 and 52999|'explore_tabs'
ERR: btw 52900 and 52999|'explore_tabs'
해당가격대 숙소 count:  111
53000 53099
ERR: btw 53000 and 53099|'explore_tabs'
해당가격대 숙소 count:  111
53100 53199
해당가격대 숙소 count:  111
53200 53299
해당가격대 숙소 count:  253
53300 53399
해당가격대 숙소 count:  142
53400 53499
해당가격대 숙소 count:  142
53500 53599
ERR: btw 53500 and 53599|'explore_tabs'
해당가격대 숙소 count:  142
53600 53699
해당가격대 숙소 count:  142
53700 53799
ERR: btw 53700 and 53799|'explore_tabs'
해당가격대 숙소 count:  142
53800 53899
해당가격대 숙소 count:  142
53900 53999
해당가격대 숙소 count:  142
54000 54099
ERR: btw 54000 and 54099|'explore_tabs'
ERR: btw 54000 and 54099|'explore_tabs'
해당가격대 숙소 count:  142
54100 54199
ERR: btw 54100 and 54199|Expecting value: line 1 column 1 (char 0)
ERR: btw 54100 and 54199|'explore_tabs'
ERR: btw 54100 and 54199|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
54100 54199
ERR: btw 54100 and 54199|'explore_tabs'
해당가격대 숙소 count:  142
54200 54299
해당가격대 숙소 count:  142
54300 54399
해당가격대 숙소 count:  142
54400 54499
해당가격대 숙소 count:  306
54500 54599
ERR: btw 54500 and 54599|'explore_tabs'
해당가격대 숙소 count:  306
54600 54699
해당가격대 숙소 count:  306
54700 54799
ERR: btw 54700 and 54799|'explore_tabs'
ERR: btw 54700 and 54799|'explore_tabs'
해당가격대 숙소 count:  306
54800 54899
해당가격대 숙소 count:  306
54900 54999
ERR: btw 54900 and 54999|'explore_tabs'
해당가격대 숙소 count:  306
55000 55099
해당가격대 숙소 count:  306
55100 55199
ERR: btw 55100 and 55199|'explore_tabs'
해당가격대 숙소 count:  306
55200 55299
ERR: btw 55200 and 55299|'explore_tabs'
해당가격대 숙소 count:  306
55300 55399
해당가격대 숙소 count:  306
55400 55499
해당가격대 숙소 count:  306
55500 55599
해당가격대 숙소 count:  306
55600 55699
해당가격대 숙소 count:  280
55700 55799
해당가격대 숙소 count:  280
55800 55899
해당가격대 숙소 count:  280
55900 55999
해당가격대 숙소 count:  280
56000 56099
해당가격대 숙소 count:  280
56100 56199
해당가격대 숙소 count:  280
56200 56299
ERR: btw 56200 and 56299|'explore_tabs'
해당가격대 숙소 count:  280
56300 56399
해당가격대 숙소 count:  280
56400 56499
ERR: btw 56400 and 56499|'explore_tabs'
해당가격대 숙소 count:  280
56500 56599
해당가격대 숙소 count:  280
56600 56699
해당가격대 숙소 count:  306
56700 56799
해당가격대 숙소 count:  96
56800 56899
해당가격대 숙소 count:  96
56900 56999
ERR: btw 56900 and 56999|'explore_tabs'
해당가격대 숙소 count:  96
57000 57099
해당가격대 숙소 count:  96
57100 57199
해당가격대 숙소 count:  96
57200 57299
ERR: btw 57200 and 57299|'explore_tabs'
해당가격대 숙소 count:  96
57300 57399
해당가격대 숙소 count:  96
57400 57499
해당가격대 숙소 count:  96
57500 57599
해당가격대 숙소 count:  96
57600 57699
해당가격대 숙소 count:  96
57700 57799
해당가격대 숙소 count:  235
57800 57899
ERR: btw 57800 and 57899|'explore_tabs'
해당가격대 숙소 count:  139
57900 57999
ERR: btw 57900 and 57999|'explore_tabs'
해당가격대 숙소 count:  139
58000 58099
해당가격대 숙소 count:  139
58100 58199
해당가격대 숙소 count:  139
58200 58299
ERR: btw 58200 and 58299|'explore_tabs'
해당가격대 숙소 count:  139
58300 58399
해당가격대 숙소 count:  139
58400 58499
해당가격대 숙소 count:  139
58500 58599
ERR: btw 58500 and 58599|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  139
58600 58699
ERR: btw 58600 and 58699|'explore_tabs'
해당가격대 숙소 count:  139
58700 58799
해당가격대 숙소 count:  139
58800 58899
해당가격대 숙소 count:  139
58900 58999
해당가격대 숙소 count:  306
59000 59099
해당가격대 숙소 count:  306
59100 59199
해당가격대 숙소 count:  306
59200 59299
해당가격대 숙소 count:  306
59300 59399
해당가격대 숙소 count:  306
59400 59499
해당가격대 숙소 count:  306
59500 59599
해당가격대 숙소 count:  306
59600 59699
해당가격대 숙소 count:  306
59700 59799
해당가격대 숙소 count:  306
59800 59899
해당가격대 숙소 count:  306
59900 59999
해당가격대 숙소 count:  306
60000 60099
ERR: btw 60000 and 60099|'explore_tabs'
해당가격대 숙소 count:  306
60100 60199
ERR: btw 60100 and 60199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  76
60200 60299
해당가격대 숙소 count:  76
60300 60399
해당가격대 숙소 count:  76
60400 60499
ERR: btw 60400 and 60499|'explore_tabs'
해당가격대 숙소 count:  76
60500 60599
해당가격대 숙소 count:  76
60600 60699
해당가격대 숙소 count:  76
60700 60799
해당가격대 숙소 count:  76
60800 60899
해당가격대 숙소 count:  76
60900 60999
해당가격대 숙소 count:  76
61000 61099
해당가격대 숙소 count:  76
61100 61199
해당가격대 숙소 count:  302
61200 61299
해당가격대 숙소 count:  226
61300 61399
해당가격대 숙소 count:  226
61400 61499
해당가격대 숙소 count:  226
61500 61599
ERR: btw 61500 and 61599|'explore_tabs'
해당가격대 숙소 count:  226
61600 61699
ERR: btw 61600 and 61699|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  226
61700 61799
해당가격대 숙소 count:  226
61800 61899
ERR: btw 61800 and 61899|'explore_tabs'
해당가격대 숙소 count:  226
61900 61999
ERR: btw 61900 and 61999|'explore_tabs'
ERR: btw 61900 and 61999|'explore_tabs'
해당가격대 숙소 count:  226
62000 62099
해당가격대 숙소 count:  226
62100 62199
해당가격대 숙소 count:  226
62200 62299
ERR: btw 62200 and 62299|'explore_tabs'
해당가격대 숙소 count:  306
62300 62399
해당가격대 숙소 count:  120
62400 62499
해당가격대 숙소 count:  120
62500 62599
해당가격대 숙소 count:  120
62600 62699
해당가격대 숙소 count:  120
62700 62799
ERR: btw 62700 and 62799|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  120
62800 62899
해당가격대 숙소 count:  120
62900 62999
해당가격대 숙소 count:  120
63000 63099
해당가격대 숙소 count:  120
63100 63199
해당가격대 숙소 count:  120
63200 63299
해당가격대 숙소 count:  120
63300 63399

해당가격대 숙소 count:  209
63400 63499
해당가격대 숙소 count:  89
63500 63599
해당가격대 숙소 count:  89
63600 63699
해당가격대 숙소 count:  89
63700 63799
해당가격대 숙소 count:  89
63800 63899
ERR: btw 63800 and 63899|'explore_tabs'
해당가격대 숙소 count:  89
63900 63999
ERR: btw 63900 and 63999|'explore_tabs'
해당가격대 숙소 count:  89
64000 64099
해당가격대 숙소 count:  89
64100 64199
해당가격대 숙소 count:  89
64200 64299
해당가격대 숙소 count:  89
64300 64399
해당가격대 숙소 count:  89
64400 64499
해당가격대 숙소 count:  89
64500 64599
해당가격대 숙소 count:  306
64600 64699
해당가격대 숙소 count:  304
64700 64799
해당가격대 숙소 count:  304
64800 64899
ERR: btw 64800 and 64899|'explore_tabs'
해당가격대 숙소 count:  304
64900 64999
해당가격대 숙소 count:  304
65000 65099
해당가격대 숙소 count:  304
65100 65199
해당가격대 숙소 count:  304
65200 65299
ERR: btw 65200 and 65299|'explore_tabs'
해당가격대 숙소 count:  304
65300 65399
해당가격대 숙소 count:  304
65400 65499
해당가격대 숙소 count:  304
65500 65599
ERR: btw 65500 and 65599|'explore_tabs'
해당가격대 숙소 count:  304
65600 65699
ERR: btw 65600 and 65699|'explore_tabs'
ERR: btw 65600 and 65699|Expecting value: line 1 column 1 (char 0)
ERR: btw 65600 and 65699|'explore_tabs'
해당 데이터 못가져옴
65600 65699
ERR: btw 65600 and 65699|'explore_tabs'
해당가격대 숙소 count:  306
65700 65799
해당가격대 숙소 count:  85
65800 65899
ERR: btw 65800 and 65899|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  85
65900 65999
해당가격대 숙소 count:  85
66000 66099
ERR: btw 66000 and 66099|'explore_tabs'
해당가격대 숙소 count:  85
66100 66199
해당가격대 숙소 count:  85
66200 66299
해당가격대 숙소 count:  85
66300 66399
해당가격대 숙소 count:  85
66400 66499
해당가격대 숙소 count:  85
66500 66599
해당가격대 숙소 count:  85
66600 66699
해당가격대 숙소 count:  85
66700 66799
ERR: btw 66700 and 66799|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  306
66800 66899
ERR: btw 66800 and 66899|'explore_tabs'
해당가격대 숙소 count:  234
66900 66999
해당가격대 숙소 count:  234
67000 67099
해당가격대 숙소 count:  234
67100 67199
해당가격대 숙소 count:  233
67200 67299
해당가격대 숙소 count:  233
67300 67399
해당가격대 숙소 count:  233
67400 67499
ERR: btw 67400 and 67499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  233
67500 67599
ERR: btw 67500 and 67599|'explore_tabs'
해당가격대 숙소 count:  233
67600 67699
해당가격대 숙소 count:  233
67700 67799
해당가격대 숙소 count:  233
67800 67899
ERR: btw 67800 and 67899|'explore_tabs'
해당가격대 숙소 count:  306
67900 67999
해당가격대 숙소 count:  144
68000 68099
해당가격대 숙소 count:  144
68100 68199
ERR: btw 68100 and 68199|'explore_tabs'
ERR: btw 68100 and 68199|'explore_tabs'
해당가격대 숙소 count:  144
68200 68299
해당가격대 숙소 count:  144
68300 68399
해당가격대 숙소 count:  144
68400 68499
해당가격대 숙소 count:  144
68500 68599
해당가격대 숙소 count:  144
68600 68699
해당가격대 숙소 count:  144
68700 68799
ERR: btw 68700 and 68799|'explore_tabs'
해당가격대 숙소 count:  144
68800 68899
해당가격대 숙소 count:  144
68900 68999
해당가격대 숙소 count:  144
69000 69099
ERR: btw 69000 and 69099|'explore_tabs'
ERR: btw 69000 and 69099|'explore_tabs'
해당가격대 숙소 count:  306
69100 69199
해당가격대 숙소 count:  306
69200 69299
해당가격대 숙소 count:  306
69300 69399
해당가격대 숙소 count:  306
69400 69499
해당가격대 숙소 count:  306
69500 69599
ERR: btw 69500 and 69599|'explore_tabs'
해당가격대 숙소 count:  306
69600 69699
ERR: btw 69600 and 69699|'explore_tabs'
해당가격대 숙소 count:  306
69700 69799
해당가격대 숙소 count:  306
69800 69899
해당가격대 숙소 count:  306
69900 69999
해당가격대 숙소 count:  306
70000 70099
해당가격대 숙소 count:  306
70100 70199
해당가격대 숙소 count:  306
70200 70299
해당가격대 숙소 count:  57
70300 70399
해당가격대 숙소 count:  57
70400 70499
해당가격대 숙소 count:  57
70500 70599
해당가격대 숙소 count:  57
70600 70699
해당가격대 숙소 count:  57
70700 70799
해당가격대 숙소 count:  57
70800 70899
해당가격대 숙소 count:  57
70900 70999
ERR: btw 70900 and 70999|'explore_tabs'
해당가격대 숙소 count:  57
71000 71099
해당가격대 숙소 count:  57
71100 71199
해당가격대 숙소 count:  57
71200 71299
ERR: btw 71200 and 71299|'explore_tabs'
해당가격대 숙소 count:  136
71300 71399
ERR: btw 71300 and 71399|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  79
71400 71499
해당가격대 숙소 count:  79
71500 71599
해당가격대 숙소 count:  79
71600 71699
ERR: btw 71600 and 71699|Expecting value: line 1 column 1 (char 0)
ERR: btw 71600 and 71699|'explore_tabs'
해당가격대 숙소 count:  79
71700 71799
ERR: btw 71700 and 71799|'explore_tabs'
ERR: btw 71700 and 71799|'explore_tabs'
ERR: btw 71700 and 71799|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
71700 71799
해당가격대 숙소 count:  79
71800 71899
해당가격대 숙소 count:  79
71900 71999
해당가격대 숙소 count:  79
72000 72099
ERR: btw 72000 and 72099|Expecting value: line 1 column 1 (char 0)
ERR: btw 72000 and 72099|'explore_tabs'
ERR: btw 72000 and 72099|'explore_tabs'
해당 데이터 못가져옴
72000 72099
해당가격대 숙소 count:  79
72100 72199
해당가격대 숙소 count:  79
72200 72299
해당가격대 숙소 count:  79
72300 72399
해당가격대 숙소 count:  205
72400 72499
해당가격대 숙소 count:  126
72500 72599
해당가격대 숙소 count:  126
72600 72699
해당가격대 숙소 count:  126
72700 72799
해당가격대 숙소 count:  126
72800 72899
해당가격대 숙소 count:  126
72900 72999
해당가격대 숙소 count:  126
73000 73099
해당가격대 숙소 count:  126
73100 73199
ERR: btw 73100 and 73199|'explore_tabs'
ERR: btw 73100 and 73199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  126
73200 73299
해당가격대 숙소 count:  126
73300 73399
해당가격대 숙소 count:  126
73400 73499
해당가격대 숙소 count:  168
73500 73599
해당가격대 숙소 count:  42
73600 73699
해당가격대 숙소 count:  42
73700 73799
해당가격대 숙소 count:  42
73800 73899
ERR: btw 73800 and 73899|'explore_tabs'
해당가격대 숙소 count:  42
73900 73999
ERR: btw 73900 and 73999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  42
74000 74099
해당가격대 숙소 count:  42
74100 74199
해당가격대 숙소 count:  42
74200 74299
해당가격대 숙소 count:  42
74300 74399
ERR: btw 74300 and 74399|'explore_tabs'
해당가격대 숙소 count:  42
74400 74499
ERR: btw 74400 and 74499|Expecting value: line 1 column 1 (char 0)
ERR: btw 74400 and 74499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  42
74500 74599
ERR: btw 74500 and 74599|'explore_tabs'
ERR: btw 74500 and 74599|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  42
74600 74699
ERR: btw 74600 and 74699|'explore_tabs'
ERR: btw 74600 and 74699|'explore_tabs'
해당가격대 숙소 count:  229
74700 74799
해당가격대 숙소 count:  187
74800 74899
해당가격대 숙소 count:  187
74900 74999
해당가격대 숙소 count:  187
75000 75099
ERR: btw 75000 and 75099|'explore_tabs'
ERR: btw 75000 and 75099|'explore_tabs'
해당가격대 숙소 count:  187
75100 75199
해당가격대 숙소 count:  187
75200 75299
해당가격대 숙소 count:  187
75300 75399
ERR: btw 75300 and 75399|'explore_tabs'
해당가격대 숙소 count:  187
75400 75499
해당가격대 숙소 count:  187
75500 75599
해당가격대 숙소 count:  187
75600 75699
해당가격대 숙소 count:  187
75700 75799
ERR: btw 75700 and 75799|Expecting value: line 1 column 1 (char 0)
ERR: btw 75700 and 75799|'explore_tabs'
해당가격대 숙소 count:  239
75800 75899
ERR: btw 75800 and 75899|'explore_tabs'
ERR: btw 75800 and 75899|'explore_tabs'
ERR: btw 75800 and 75899|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
75800 75899
해당가격대 숙소 count:  52
75900 75999
해당가격대 숙소 count:  52
76000 76099
해당가격대 숙소 count:  52
76100 76199
ERR: btw 76100 and 76199|'explore_tabs'
해당가격대 숙소 count:  52
76200 76299
ERR: btw 76200 and 76299|Expecting value: line 1 column 1 (char 0)
ERR: btw 76200 and 76299|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
76300 76399
ERR: btw 76300 and 76399|'explore_tabs'
해당가격대 숙소 count:  52
76400 76499
해당가격대 숙소 count:  52
76500 76599
해당가격대 숙소 count:  52
76600 76699
ERR: btw 76600 and 76699|'explore_tabs'
ERR: btw 76600 and 76699|'explore_tabs'
해당가격대 숙소 count:  52
76700 76799
해당가격대 숙소 count:  52
76800 76899
해당가격대 숙소 count:  119
76900 76999
해당가격대 숙소 count:  67
77000 77099
ERR: btw 77000 and 77099|'explore_tabs'
해당가격대 숙소 count:  67
77100 77199
해당가격대 숙소 count:  67
77200 77299
해당가격대 숙소 count:  67
77300 77399
해당가격대 숙소 count:  67
77400 77499
ERR: btw 77400 and 77499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  67
77500 77599
해당가격대 숙소 count:  67
77600 77699
해당가격대 숙소 count:  67
77700 77799
해당가격대 숙소 count:  67
77800 77899
ERR: btw 77800 and 77899|'explore_tabs'
해당가격대 숙소 count:  67
77900 77999
해당가격대 숙소 count:  267
78000 78099
해당가격대 숙소 count:  200
78100 78199
해당가격대 숙소 count:  200
78200 78299
ERR: btw 78200 and 78299|'explore_tabs'
해당가격대 숙소 count:  200
78300 78399
해당가격대 숙소 count:  200
78400 78499
ERR: btw 78400 and 78499|'explore_tabs'
해당가격대 숙소 count:  200
78500 78599
ERR: btw 78500 and 78599|'explore_tabs'
ERR: btw 78500 and 78599|'explore_tabs'
해당가격대 숙소 count:  200
78600 78699

ERR: btw 78600 and 78699|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  200
78700 78799
ERR: btw 78700 and 78799|Expecting value: line 1 column 1 (char 0)
ERR: btw 78700 and 78799|'explore_tabs'
ERR: btw 78700 and 78799|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
78700 78799
ERR: btw 78700 and 78799|'explore_tabs'
ERR: btw 78700 and 78799|'explore_tabs'
해당가격대 숙소 count:  200
78800 78899
해당가격대 숙소 count:  200
78900 78999
해당가격대 숙소 count:  200
79000 79099
ERR: btw 79000 and 79099|Expecting value: line 1 column 1 (char 0)
ERR: btw 79000 and 79099|'explore_tabs'
해당가격대 숙소 count:  200
79100 79199
해당가격대 숙소 count:  306
79200 79299
해당가격대 숙소 count:  289
79300 79399
해당가격대 숙소 count:  289
79400 79499
ERR: btw 79400 and 79499|'explore_tabs'
ERR: btw 79400 and 79499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  289
79500 79599
ERR: btw 79500 and 79599|'explore_tabs'
해당가격대 숙소 count:  289
79600 79699
해당가격대 숙소 count:  289
79700 79799
해당가격대 숙소 count:  289
79800 79899
해당가격대 숙소 count:  289
79900 79999
ERR: btw 79900 and 79999|'explore_tabs'
해당가격대 숙소 count:  289
80000 80099
해당가격대 숙소 count:  289
80100 80199
ERR: btw 80100 and 80199|Expecting value: line 1 column 1 (char 0)
ERR: btw 80100 and 80199|Expecting value: line 1 column 1 (char 0)
ERR: btw 80100 and 80199|'explore_tabs'
해당 데이터 못가져옴
80100 80199
해당가격대 숙소 count:  289
80200 80299
해당가격대 숙소 count:  306
80300 80399
ERR: btw 80300 and 80399|Expecting value: line 1 column 1 (char 0)
ERR: btw 80300 and 80399|'explore_tabs'
해당가격대 숙소 count:  38
80400 80499
해당가격대 숙소 count:  38
80500 80599
해당가격대 숙소 count:  38
80600 80699
해당가격대 숙소 count:  38
80700 80799
해당가격대 숙소 count:  38
80800 80899
ERR: btw 80800 and 80899|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  38
80900 80999
해당가격대 숙소 count:  38
81000 81099
ERR: btw 81000 and 81099|'explore_tabs'
ERR: btw 81000 and 81099|'explore_tabs'
해당가격대 숙소 count:  38
81100 81199
해당가격대 숙소 count:  38
81200 81299
ERR: btw 81200 and 81299|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  38
81300 81399
해당가격대 숙소 count:  82
81400 81499
해당가격대 숙소 count:  44
81500 81599
ERR: btw 81500 and 81599|Expecting value: line 1 column 1 (char 0)
ERR: btw 81500 and 81599|Expecting value: line 1 column 1 (char 0)
ERR: btw 81500 and 81599|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
81500 81599
해당가격대 숙소 count:  44
81600 81699
ERR: btw 81600 and 81699|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  44
81700 81799
해당가격대 숙소 count:  44
81800 81899
해당가격대 숙소 count:  44
81900 81999
해당가격대 숙소 count:  44
82000 82099
ERR: btw 82000 and 82099|'explore_tabs'
해당가격대 숙소 count:  44
82100 82199
ERR: btw 82100 and 82199|Expecting value: line 1 column 1 (char 0)
ERR: btw 82100 and 82199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  44
82200 82299
ERR: btw 82200 and 82299|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  44
82300 82399
해당가격대 숙소 count:  44
82400 82499
ERR: btw 82400 and 82499|'explore_tabs'
ERR: btw 82400 and 82499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  83
82500 82599
ERR: btw 82500 and 82599|'explore_tabs'
ERR: btw 82500 and 82599|'explore_tabs'
ERR: btw 82500 and 82599|'explore_tabs'
해당 데이터 못가져옴
82500 82599
해당가격대 숙소 count:  39
82600 82699
해당가격대 숙소 count:  39
82700 82799
해당가격대 숙소 count:  39
82800 82899
해당가격대 숙소 count:  39
82900 82999
해당가격대 숙소 count:  39
83000 83099
ERR: btw 83000 and 83099|'explore_tabs'
ERR: btw 83000 and 83099|'explore_tabs'
ERR: btw 83000 and 83099|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
83000 83099
ERR: btw 83000 and 83099|'explore_tabs'
ERR: btw 83000 and 83099|'explore_tabs'
ERR: btw 83000 and 83099|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
83000 83099
해당가격대 숙소 count:  39
83100 83199
해당가격대 숙소 count:  39
83200 83299
해당가격대 숙소 count:  39
83300 83399
ERR: btw 83300 and 83399|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  39
83400 83499
해당가격대 숙소 count:  39
83500 83599
해당가격대 숙소 count:  113
83600 83699
해당가격대 숙소 count:  74
83700 83799
ERR: btw 83700 and 83799|Expecting value: line 1 column 1 (char 0)
ERR: btw 83700 and 83799|'explore_tabs'
해당가격대 숙소 count:  74
83800 83899
ERR: btw 83800 and 83899|'explore_tabs'
해당가격대 숙소 count:  74
83900 83999
해당가격대 숙소 count:  74
84000 84099
ERR: btw 84000 and 84099|'explore_tabs'
해당가격대 숙소 count:  74
84100 84199
해당가격대 숙소 count:  74
84200 84299
해당가격대 숙소 count:  74
84300 84399
ERR: btw 84300 and 84399|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  74
84400 84499
ERR: btw 84400 and 84499|'explore_tabs'
해당가격대 숙소 count:  74
84500 84599
ERR: btw 84500 and 84599|Expecting value: line 1 column 1 (char 0)
ERR: btw 84500 and 84599|'explore_tabs'
해당가격대 숙소 count:  74
84600 84699
ERR: btw 84600 and 84699|'explore_tabs'
해당가격대 숙소 count:  74
84700 84799
해당가격대 숙소 count:  211
84800 84899
해당가격대 숙소 count:  137
84900 84999
ERR: btw 84900 and 84999|'explore_tabs'
ERR: btw 84900 and 84999|'explore_tabs'
해당가격대 숙소 count:  137
85000 85099
해당가격대 숙소 count:  137
85100 85199
해당가격대 숙소 count:  137
85200 85299
ERR: btw 85200 and 85299|'explore_tabs'
해당가격대 숙소 count:  137
85300 85399
해당가격대 숙소 count:  137
85400 85499
해당가격대 숙소 count:  137
85500 85599
ERR: btw 85500 and 85599|'explore_tabs'
ERR: btw 85500 and 85599|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  137
85600 85699
ERR: btw 85600 and 85699|'explore_tabs'
해당가격대 숙소 count:  137
85700 85799
ERR: btw 85700 and 85799|'explore_tabs'
해당가격대 숙소 count:  137
85800 85899
해당가격대 숙소 count:  168
85900 85999
해당가격대 숙소 count:  31
86000 86099
ERR: btw 86000 and 86099|'explore_tabs'
해당가격대 숙소 count:  31
86100 86199
해당가격대 숙소 count:  31
86200 86299
ERR: btw 86200 and 86299|'explore_tabs'
해당가격대 숙소 count:  31
86300 86399
해당가격대 숙소 count:  31
86400 86499
ERR: btw 86400 and 86499|Expecting value: line 1 column 1 (char 0)
ERR: btw 86400 and 86499|'explore_tabs'
ERR: btw 86400 and 86499|'explore_tabs'
해당 데이터 못가져옴
86400 86499
해당가격대 숙소 count:  31
86500 86599
ERR: btw 86500 and 86599|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  31
86600 86699
해당가격대 숙소 count:  31
86700 86799
해당가격대 숙소 count:  31
86800 86899
해당가격대 숙소 count:  31
86900 86999
해당가격대 숙소 count:  75
87000 87099
해당가격대 숙소 count:  44
87100 87199
ERR: btw 87100 and 87199|'explore_tabs'
해당가격대 숙소 count:  44
87200 87299
해당가격대 숙소 count:  44
87300 87399
해당가격대 숙소 count:  44
87400 87499
해당가격대 숙소 count:  44
87500 87599
해당가격대 숙소 count:  44
87600 87699
해당가격대 숙소 count:  44
87700 87799
ERR: btw 87700 and 87799|'explore_tabs'
해당가격대 숙소 count:  44
87800 87899
해당가격대 숙소 count:  44
87900 87999
ERR: btw 87900 and 87999|'explore_tabs'
해당가격대 숙소 count:  44
88000 88099
해당가격대 숙소 count:  96
88100 88199
ERR: btw 88100 and 88199|Expecting value: line 1 column 1 (char 0)
ERR: btw 88100 and 88199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
88200 88299
해당가격대 숙소 count:  52
88300 88399
ERR: btw 88300 and 88399|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
88400 88499
해당가격대 숙소 count:  52
88500 88599
해당가격대 숙소 count:  52
88600 88699
해당가격대 숙소 count:  52
88700 88799
ERR: btw 88700 and 88799|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
88800 88899
ERR: btw 88800 and 88899|Expecting value: line 1 column 1 (char 0)
ERR: btw 88800 and 88899|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
88900 88999
ERR: btw 88900 and 88999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
89000 89099
해당가격대 숙소 count:  52
89100 89199
ERR: btw 89100 and 89199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  52
89200 89299
ERR: btw 89200 and 89299|'explore_tabs'
ERR: btw 89200 and 89299|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  286
89300 89399
해당가격대 숙소 count:  234
89400 89499
ERR: btw 89400 and 89499|Expecting value: line 1 column 1 (char 0)
ERR: btw 89400 and 89499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  234
89500 89599
해당가격대 숙소 count:  234
89600 89699
ERR: btw 89600 and 89699|'explore_tabs'
해당가격대 숙소 count:  234
89700 89799
해당가격대 숙소 count:  234
89800 89899
해당가격대 숙소 count:  234
89900 89999
해당가격대 숙소 count:  234
90000 90099
ERR: btw 90000 and 90099|'explore_tabs'
해당가격대 숙소 count:  234
90100 90199
해당가격대 숙소 count:  234
90200 90299
해당가격대 숙소 count:  234
90300 90399
ERR: btw 90300 and 90399|'explore_tabs'

해당가격대 숙소 count:  244
90400 90499
ERR: btw 90400 and 90499|'explore_tabs'
해당가격대 숙소 count:  11
90500 90599
해당가격대 숙소 count:  11
90600 90699
해당가격대 숙소 count:  11
90700 90799
ERR: btw 90700 and 90799|'explore_tabs'
ERR: btw 90700 and 90799|'explore_tabs'
ERR: btw 90700 and 90799|'explore_tabs'
해당 데이터 못가져옴
90700 90799
해당가격대 숙소 count:  11
90800 90899
해당가격대 숙소 count:  11
90900 90999
해당가격대 숙소 count:  11
91000 91099
ERR: btw 91000 and 91099|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  11
91100 91199
ERR: btw 91100 and 91199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  11
91200 91299
ERR: btw 91200 and 91299|'explore_tabs'
해당가격대 숙소 count:  11
91300 91399
해당가격대 숙소 count:  11
91400 91499
해당가격대 숙소 count:  32
91500 91599
해당가격대 숙소 count:  22
91600 91699
해당가격대 숙소 count:  22
91700 91799
해당가격대 숙소 count:  22
91800 91899
해당가격대 숙소 count:  22
91900 91999
해당가격대 숙소 count:  22
92000 92099
해당가격대 숙소 count:  22
92100 92199
해당가격대 숙소 count:  22
92200 92299
해당가격대 숙소 count:  22
92300 92399
ERR: btw 92300 and 92399|'explore_tabs'
해당가격대 숙소 count:  22
92400 92499
ERR: btw 92400 and 92499|'explore_tabs'
해당가격대 숙소 count:  22
92500 92599
해당가격대 숙소 count:  49
92600 92699
해당가격대 숙소 count:  27
92700 92799
ERR: btw 92700 and 92799|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  27
92800 92899
해당가격대 숙소 count:  27
92900 92999
해당가격대 숙소 count:  27
93000 93099
ERR: btw 93000 and 93099|Expecting value: line 1 column 1 (char 0)
ERR: btw 93000 and 93099|Expecting value: line 1 column 1 (char 0)
ERR: btw 93000 and 93099|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
93000 93099
해당가격대 숙소 count:  27
93100 93199
해당가격대 숙소 count:  27
93200 93299
ERR: btw 93200 and 93299|'explore_tabs'
해당가격대 숙소 count:  27
93300 93399
ERR: btw 93300 and 93399|'explore_tabs'
ERR: btw 93300 and 93399|'explore_tabs'
해당가격대 숙소 count:  27
93400 93499
해당가격대 숙소 count:  27
93500 93599
ERR: btw 93500 and 93599|Expecting value: line 1 column 1 (char 0)
ERR: btw 93500 and 93599|'explore_tabs'
해당가격대 숙소 count:  27
93600 93699
해당가격대 숙소 count:  58
93700 93799
ERR: btw 93700 and 93799|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  31
93800 93899
해당가격대 숙소 count:  31
93900 93999
해당가격대 숙소 count:  31
94000 94099
해당가격대 숙소 count:  31
94100 94199
ERR: btw 94100 and 94199|'explore_tabs'
ERR: btw 94100 and 94199|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  31
94200 94299
해당가격대 숙소 count:  31
94300 94399
해당가격대 숙소 count:  31
94400 94499
해당가격대 숙소 count:  31
94500 94599
해당가격대 숙소 count:  31
94600 94699
해당가격대 숙소 count:  31
94700 94799
해당가격대 숙소 count:  31
94800 94899
해당가격대 숙소 count:  139
94900 94999
ERR: btw 94900 and 94999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  108
95000 95099
해당가격대 숙소 count:  108
95100 95199
해당가격대 숙소 count:  108
95200 95299
해당가격대 숙소 count:  108
95300 95399
ERR: btw 95300 and 95399|'explore_tabs'
ERR: btw 95300 and 95399|'explore_tabs'
해당가격대 숙소 count:  108
95400 95499
ERR: btw 95400 and 95499|'explore_tabs'
해당가격대 숙소 count:  108
95500 95599
ERR: btw 95500 and 95599|'explore_tabs'
ERR: btw 95500 and 95599|'explore_tabs'
해당가격대 숙소 count:  108
95600 95699
해당가격대 숙소 count:  108
95700 95799
해당가격대 숙소 count:  108
95800 95899
해당가격대 숙소 count:  108
95900 95999
해당가격대 숙소 count:  127
96000 96099
해당가격대 숙소 count:  19
96100 96199
해당가격대 숙소 count:  19
96200 96299
ERR: btw 96200 and 96299|Expecting value: line 1 column 1 (char 0)
ERR: btw 96200 and 96299|'explore_tabs'
ERR: btw 96200 and 96299|'explore_tabs'
해당 데이터 못가져옴
96200 96299
해당가격대 숙소 count:  19
96300 96399
해당가격대 숙소 count:  19
96400 96499
ERR: btw 96400 and 96499|'explore_tabs'
해당가격대 숙소 count:  19
96500 96599
해당가격대 숙소 count:  19
96600 96699
해당가격대 숙소 count:  19
96700 96799
해당가격대 숙소 count:  19
96800 96899
해당가격대 숙소 count:  19
96900 96999
해당가격대 숙소 count:  19
97000 97099
해당가격대 숙소 count:  49
97100 97199
해당가격대 숙소 count:  30
97200 97299
해당가격대 숙소 count:  30
97300 97399
해당가격대 숙소 count:  30
97400 97499
해당가격대 숙소 count:  30
97500 97599
해당가격대 숙소 count:  30
97600 97699
ERR: btw 97600 and 97699|'explore_tabs'
ERR: btw 97600 and 97699|'explore_tabs'
해당가격대 숙소 count:  30
97700 97799
해당가격대 숙소 count:  30
97800 97899
ERR: btw 97800 and 97899|'explore_tabs'
해당가격대 숙소 count:  30
97900 97999
ERR: btw 97900 and 97999|'explore_tabs'
ERR: btw 97900 and 97999|'explore_tabs'
해당가격대 숙소 count:  30
98000 98099
ERR: btw 98000 and 98099|'explore_tabs'
ERR: btw 98000 and 98099|'explore_tabs'
해당가격대 숙소 count:  30
98100 98199
해당가격대 숙소 count:  65
98200 98299
해당가격대 숙소 count:  35
98300 98399
해당가격대 숙소 count:  35
98400 98499
해당가격대 숙소 count:  35
98500 98599
해당가격대 숙소 count:  35
98600 98699
ERR: btw 98600 and 98699|'explore_tabs'
해당가격대 숙소 count:  35
98700 98799
해당가격대 숙소 count:  35
98800 98899
해당가격대 숙소 count:  35
98900 98999
해당가격대 숙소 count:  35
99000 99099
해당가격대 숙소 count:  35
99100 99199
해당가격대 숙소 count:  35
99200 99299
해당가격대 숙소 count:  35
99300 99399
해당가격대 숙소 count:  279
99400 99499
ERR: btw 99400 and 99499|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  244
99500 99599
해당가격대 숙소 count:  244
99600 99699
ERR: btw 99600 and 99699|'explore_tabs'
ERR: btw 99600 and 99699|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  244
99700 99799
해당가격대 숙소 count:  244
99800 99899
ERR: btw 99800 and 99899|'explore_tabs'
해당가격대 숙소 count:  244
99900 99999
해당가격대 숙소 count:  244
100000 100099
해당가격대 숙소 count:  244
101000 101999
해당가격대 숙소 count:  66
102000 102999
ERR: btw 102000 and 102999|'explore_tabs'
해당가격대 숙소 count:  36
103000 103999
해당가격대 숙소 count:  27
104000 104999
해당가격대 숙소 count:  29
105000 105999
ERR: btw 105000 and 105999|'explore_tabs'
ERR: btw 105000 and 105999|'explore_tabs'
ERR: btw 105000 and 105999|'explore_tabs'
해당 데이터 못가져옴
105000 105999
해당가격대 숙소 count:  20
106000 106999
해당가격대 숙소 count:  45
107000 107999
해당가격대 숙소 count:  46
108000 108999
ERR: btw 108000 and 108999|'explore_tabs'
해당가격대 숙소 count:  35
109000 109999
해당가격대 숙소 count:  98
110000 110999
해당가격대 숙소 count:  112
111000 111999
해당가격대 숙소 count:  99
112000 112999
해당가격대 숙소 count:  76
113000 113999
해당가격대 숙소 count:  21
114000 114999
해당가격대 숙소 count:  16
115000 115999
ERR: btw 115000 and 115999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  20
116000 116999
ERR: btw 116000 and 116999|'explore_tabs'
ERR: btw 116000 and 116999|'explore_tabs'
해당가격대 숙소 count:  11
117000 117999
해당가격대 숙소 count:  36
118000 118999
해당가격대 숙소 count:  42
119000 119999
해당가격대 숙소 count:  139
120000 120999
해당가격대 숙소 count:  138
121000 121999
해당가격대 숙소 count:  23
122000 122999
해당가격대 숙소 count:  36
123000 123999
ERR: btw 123000 and 123999|Expecting value: line 1 column 1 (char 0)
ERR: btw 123000 and 123999|'explore_tabs'
해당가격대 숙소 count:  51
124000 124999
해당가격대 숙소 count:  26
125000 125999
해당가격대 숙소 count:  38
126000 126999
해당가격대 숙소 count:  15
127000 127999
ERR: btw 127000 and 127999|'explore_tabs'
해당가격대 숙소 count:  15
128000 128999
해당가격대 숙소 count:  18
129000 129999
해당가격대 숙소 count:  84
130000 130999
해당가격대 숙소 count:  81
131000 131999
ERR: btw 131000 and 131999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  6
132000 132999
ERR: btw 132000 and 132999|'explore_tabs'
해당가격대 숙소 count:  13
133000 133999
ERR: btw 133000 and 133999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  11
134000 134999
해당가격대 숙소 count:  70
135000 135999
해당가격대 숙소 count:  65
136000 136999
해당가격대 숙소 count:  14
137000 137999
ERR: btw 137000 and 137999|Expecting value: line 1 column 1 (char 0)
ERR: btw 137000 and 137999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  13
138000 138999
ERR: btw 138000 and 138999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  22
139000 139999
ERR: btw 139000 and 139999|Expecting value: line 1 column 1 (char 0)
ERR: btw 139000 and 139999|'explore_tabs'
ERR: btw 139000 and 139999|'explore_tabs'
해당 데이터 못가져옴
139000 139999
ERR: btw 139000 and 139999|'explore_tabs'
해당가격대 숙소 count:  69
140000 140999
ERR: btw 140000 and 140999|Expecting value: line 1 column 1 (char 0)
ERR: btw 140000 and 140999|Expecting value: line 1 column 1 (char 0)
ERR: btw 140000 and 140999|'explore_tabs'
해당 데이터 못가져옴
140000 140999
해당가격대 숙소 count:  62
141000 141999
해당가격대 숙소 count:  21
142000 142999
해당가격대 숙소 count:  13
143000 143999
ERR: btw 143000 and 143999|'explore_tabs'
ERR: btw 143000 and 143999|Expecting value: line 1 column 1 (char 0)

해당가격대 숙소 count:  22
144000 144999
해당가격대 숙소 count:  28
145000 145999
ERR: btw 145000 and 145999|'explore_tabs'
ERR: btw 145000 and 145999|'explore_tabs'
해당가격대 숙소 count:  32
146000 146999
해당가격대 숙소 count:  22
147000 147999
해당가격대 숙소 count:  6
148000 148999
해당가격대 숙소 count:  18
149000 149999
해당가격대 숙소 count:  126
150000 150999
해당가격대 숙소 count:  123
151000 151999
해당가격대 숙소 count:  9
152000 152999
해당가격대 숙소 count:  13
153000 153999
해당가격대 숙소 count:  8
154000 154999
해당가격대 숙소 count:  18
155000 155999
해당가격대 숙소 count:  17
156000 156999
해당가격대 숙소 count:  11
157000 157999
해당가격대 숙소 count:  12
158000 158999
해당가격대 숙소 count:  14
159000 159999
해당가격대 숙소 count:  53
160000 160999
해당가격대 숙소 count:  45
161000 161999
ERR: btw 161000 and 161999|'explore_tabs'
ERR: btw 161000 and 161999|'explore_tabs'
해당가격대 숙소 count:  47
162000 162999
해당가격대 숙소 count:  8
163000 163999
해당가격대 숙소 count:  7
164000 164999
ERR: btw 164000 and 164999|'explore_tabs'
ERR: btw 164000 and 164999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  8
165000 165999
해당가격대 숙소 count:  12
166000 166999
해당가격대 숙소 count:  6
167000 167999
해당가격대 숙소 count:  35
168000 168999
해당가격대 숙소 count:  38
169000 169999
해당가격대 숙소 count:  25
170000 170999
해당가격대 숙소 count:  21
171000 171999
해당가격대 숙소 count:  22
172000 172999
해당가격대 숙소 count:  4
173000 173999
해당가격대 숙소 count:  11
174000 174999
해당가격대 숙소 count:  12
175000 175999
해당가격대 숙소 count:  8
176000 176999
해당가격대 숙소 count:  5
177000 177999
해당가격대 숙소 count:  4
178000 178999
해당가격대 숙소 count:  64
179000 179999
해당가격대 숙소 count:  62
180000 180999
해당가격대 숙소 count:  64
181000 181999
해당가격대 숙소 count:  5
182000 182999
해당가격대 숙소 count:  4
183000 183999
ERR: btw 183000 and 183999|'explore_tabs'
해당가격대 숙소 count:  6
184000 184999
ERR: btw 184000 and 184999|'explore_tabs'
해당가격대 숙소 count:  13
185000 185999
해당가격대 숙소 count:  8
186000 186999
해당가격대 숙소 count:  1
187000 187999
해당가격대 숙소 count:  4
188000 188999
해당가격대 숙소 count:  3
189000 189999
해당가격대 숙소 count:  21
190000 190999
해당가격대 숙소 count:  31
191000 191999
해당가격대 숙소 count:  14
192000 192999
해당가격대 숙소 count:  3
193000 193999
해당가격대 숙소 count:  2
194000 194999
해당가격대 숙소 count:  5
195000 195999
해당가격대 숙소 count:  8
196000 196999
해당가격대 숙소 count:  8
197000 197999
해당가격대 숙소 count:  4
198000 198999
해당가격대 숙소 count:  6
199000 199999
해당가격대 숙소 count:  88
200000 200999
해당가격대 숙소 count:  90
201000 201999
해당가격대 숙소 count:  19
202000 202999
해당가격대 숙소 count:  17
203000 203999
해당가격대 숙소 count:  2
204000 204999
해당가격대 숙소 count:  1
205000 205999
해당가격대 숙소 count:  1
206000 206999
해당가격대 숙소 count:  1
207000 207999
해당가격대 숙소 count:  3
208000 208999
해당가격대 숙소 count:  5
209000 209999
해당가격대 숙소 count:  16
210000 210999
해당가격대 숙소 count:  15
211000 211999
해당가격대 숙소 count:  3
212000 212999
해당가격대 숙소 count:  7
213000 213999
해당가격대 숙소 count:  6
214000 214999
해당가격대 숙소 count:  1
215000 215999
해당가격대 숙소 count:  2
216000 216999
해당가격대 숙소 count:  1
217000 217999
해당가격대 숙소 count:  3
218000 218999
해당가격대 숙소 count:  4
219000 219999
해당가격대 숙소 count:  21
220000 220999
해당가격대 숙소 count:  19
221000 221999
해당가격대 숙소 count:  5
222000 222999
해당가격대 숙소 count:  13
223000 223999
해당가격대 숙소 count:  26
224000 224999
해당가격대 숙소 count:  22
225000 225999
해당가격대 숙소 count:  2
226000 226999
해당가격대 숙소 count:  2
227000 227999
해당가격대 숙소 count:  2
228000 228999
해당가격대 숙소 count:  2
229000 229999
해당가격대 숙소 count:  11
230000 230999
해당가격대 숙소 count:  11
231000 231999
해당가격대 숙소 count:  1
232000 232999
해당가격대 숙소 count:  3
233000 233999
해당가격대 숙소 count:  7
234000 234999
해당가격대 숙소 count:  5
235000 235999
해당가격대 숙소 count:  10
236000 236999
해당가격대 숙소 count:  7
237000 237999
ERR: btw 237000 and 237999|'explore_tabs'
해당가격대 숙소 count:  4
238000 238999
해당가격대 숙소 count:  5
239000 239999
해당가격대 숙소 count:  11
240000 240999
해당가격대 숙소 count:  8
241000 241999
해당가격대 숙소 count:  3
242000 242999
해당가격대 숙소 count:  3
243000 243999
244000 244999
해당가격대 숙소 count:  1
245000 245999
해당가격대 숙소 count:  1
246000 246999
ERR: btw 246000 and 246999|'explore_tabs'
해당가격대 숙소 count:  3
247000 247999
해당가격대 숙소 count:  5
248000 248999
해당가격대 숙소 count:  3
249000 249999
해당가격대 숙소 count:  54
250000 250999
해당가격대 숙소 count:  53
251000 251999
해당가격대 숙소 count:  1
252000 252999
해당가격대 숙소 count:  1
253000 253999
해당가격대 숙소 count:  5
254000 254999
해당가격대 숙소 count:  5
255000 255999
ERR: btw 255000 and 255999|'explore_tabs'
해당가격대 숙소 count:  2
256000 256999
해당가격대 숙소 count:  3
257000 257999
해당가격대 숙소 count:  6
258000 258999
해당가격대 숙소 count:  7
259000 259999
해당가격대 숙소 count:  12
260000 260999
ERR: btw 260000 and 260999|'explore_tabs'
해당가격대 숙소 count:  11
261000 261999
해당가격대 숙소 count:  2
262000 262999
해당가격대 숙소 count:  4
263000 263999
해당가격대 숙소 count:  3
264000 264999
해당가격대 숙소 count:  5
265000 265999
해당가격대 숙소 count:  4
266000 266999
267000 267999
268000 268999
해당가격대 숙소 count:  1
269000 269999
해당가격대 숙소 count:  18
270000 270999
해당가격대 숙소 count:  17
271000 271999
272000 272999
273000 273999
274000 274999
해당가격대 숙소 count:  5
275000 275999
해당가격대 숙소 count:  5
276000 276999
해당가격대 숙소 count:  1
277000 277999
해당가격대 숙소 count:  3
278000 278999
해당가격대 숙소 count:  3
279000 279999
해당가격대 숙소 count:  28
280000 280999
해당가격대 숙소 count:  27
281000 281999
해당가격대 숙소 count:  28
282000 282999
해당가격대 숙소 count:  1
283000 283999
해당가격대 숙소 count:  2
284000 284999
해당가격대 숙소 count:  2
285000 285999
해당가격대 숙소 count:  1
286000 286999
해당가격대 숙소 count:  1
287000 287999
288000 288999
해당가격대 숙소 count:  11
289000 289999
해당가격대 숙소 count:  11
290000 290999
해당가격대 숙소 count:  11
291000 291999
해당가격대 숙소 count:  2
292000 292999
해당가격대 숙소 count:  2
293000 293999
294000 294999
해당가격대 숙소 count:  1
295000 295999
해당가격대 숙소 count:  1
296000 296999
해당가격대 숙소 count:  1
297000 297999
해당가격대 숙소 count:  3
298000 298999
해당가격대 숙소 count:  2
299000 299999
해당가격대 숙소 count:  35
300000 300999
해당가격대 숙소 count:  33
301000 301999
302000 302999
해당가격대 숙소 count:  3
303000 303999
해당가격대 숙소 count:  3
304000 304999
305000 305999
ERR: btw 305000 and 305999|'explore_tabs'
306000 306999
307000 307999
308000 308999
해당가격대 숙소 count:  1
309000 309999
해당가격대 숙소 count:  7
310000 310999
해당가격대 숙소 count:  6
311000 311999
해당가격대 숙소 count:  1
312000 312999
해당가격대 숙소 count:  1
313000 313999
해당가격대 숙소 count:  6
314000 314999
해당가격대 숙소 count:  7
315000 315999
해당가격대 숙소 count:  1
316000 316999
해당가격대 숙소 count:  1
317000 317999
해당가격대 숙소 count:  1
318000 318999
해당가격대 숙소 count:  2
319000 319999
해당가격대 숙소 count:  14
320000 320999
해당가격대 숙소 count:  15
321000 321999
해당가격대 숙소 count:  3
322000 322999
해당가격대 숙소 count:  1
323000 323999
324000 324999
해당가격대 숙소 count:  3
325000 325999
해당가격대 숙소 count:  4
326000 326999
해당가격대 숙소 count:  1
327000 327999
해당가격대 숙소 count:  1
328000 328999
해당가격대 숙소 count:  1
329000 329999
해당가격대 숙소 count:  10
330000 330999
해당가격대 숙소 count:  10
331000 331999
해당가격대 숙소 count:  1
332000 332999
333000 333999
334000 334999
해당가격대 숙소 count:  8
335000 335999
해당가격대 숙소 count:  8
336000 336999
해당가격대 숙소 count:  19
337000 337999
해당가격대 숙소 count:  11
338000 338999
해당가격대 숙소 count:  3
339000 339999
해당가격대 숙소 count:  6
340000 340999
해당가격대 숙소 count:  3
341000 341999
342000 342999
343000 343999
해당가격대 숙소 count:  1
344000 344999
해당가격대 숙소 count:  1
345000 345999
해당가격대 숙소 count:  1
346000 346999
347000 347999
348000 348999
해당가격대 숙소 count:  1
349000 349999
해당가격대 숙소 count:  18
350000 350999
해당가격대 숙소 count:  19
351000 351999
해당가격대 숙소 count:  1
352000 352999
353000 353999
354000 354999
해당가격대 숙소 count:  1
355000 355999
해당가격대 숙소 count:  1
356000 356999
357000 357999
358000 358999
해당가격대 숙소 count:  5
359000 359999
해당가격대 숙소 count:  8
360000 360999
해당가격대 숙소 count:  3
361000 361999
362000 362999
363000 363999
364000 364999
365000 365999
366000 366999
367000 367999
368000 368999
해당가격대 숙소 count:  1
369000 369999
해당가격대 숙소 count:  4
370000 370999
해당가격대 숙소 count:  3
371000 371999
372000 372999
373000 373999
374000 374999
375000 375999
376000 376999
377000 377999
378000 378999
379000 379999
해당가격대 숙소 count:  8
380000 380999
해당가격대 숙소 count:  8
381000 381999
382000 382999
383000 383999
384000 384999
해당가격대 숙소 count:  1
385000 385999
해당가격대 숙소 count:  1
386000 386999
387000 387999
388000 388999
389000 389999
해당가격대 숙소 count:  6
390000 390999
해당가격대 숙소 count:  6
391000 391999
해당가격대 숙소 count:  6
392000 392999
해당가격대 숙소 count:  13
393000 393999
해당가격대 숙소 count:  13
394000 394999
395000 395999
396000 396999
397000 397999
398000 398999
해당가격대 숙소 count:  17
399000 399999
해당가격대 숙소 count:  17
400000 400999

해당가격대 숙소 count:  17
401000 401999
402000 402999
해당가격대 숙소 count:  1
403000 403999
해당가격대 숙소 count:  1
404000 404999
405000 405999
406000 406999
407000 407999
408000 408999
해당가격대 숙소 count:  1
409000 409999
해당가격대 숙소 count:  1
410000 410999
해당가격대 숙소 count:  1
411000 411999
412000 412999
413000 413999
414000 414999
415000 415999
416000 416999
417000 417999
418000 418999
419000 419999
해당가격대 숙소 count:  1
420000 420999
해당가격대 숙소 count:  1
421000 421999
422000 422999
423000 423999
424000 424999
425000 425999
426000 426999
427000 427999
428000 428999
429000 429999
해당가격대 숙소 count:  2
430000 430999
해당가격대 숙소 count:  2
431000 431999
432000 432999
433000 433999
434000 434999
435000 435999
436000 436999
437000 437999
438000 438999
439000 439999
해당가격대 숙소 count:  3
440000 440999
해당가격대 숙소 count:  3
441000 441999
442000 442999
443000 443999
444000 444999
445000 445999
446000 446999
447000 447999
해당가격대 숙소 count:  1
448000 448999
해당가격대 숙소 count:  6
449000 449999
해당가격대 숙소 count:  18
450000 450999
해당가격대 숙소 count:  13
451000 451999
해당가격대 숙소 count:  1
452000 452999
해당가격대 숙소 count:  1
453000 453999
454000 454999
455000 455999
456000 456999
457000 457999
458000 458999
459000 459999
460000 460999
461000 461999
462000 462999
463000 463999
해당가격대 숙소 count:  1
464000 464999
해당가격대 숙소 count:  1
465000 465999
해당가격대 숙소 count:  1
466000 466999
해당가격대 숙소 count:  1
467000 467999
해당가격대 숙소 count:  1
468000 468999
469000 469999
해당가격대 숙소 count:  1
470000 470999
해당가격대 숙소 count:  2
471000 471999
해당가격대 숙소 count:  1
472000 472999
473000 473999
474000 474999
475000 475999
476000 476999
477000 477999
478000 478999
479000 479999
해당가격대 숙소 count:  4
480000 480999
해당가격대 숙소 count:  4
481000 481999
482000 482999
483000 483999
484000 484999
485000 485999
486000 486999
해당가격대 숙소 count:  1
487000 487999
해당가격대 숙소 count:  1
488000 488999
해당가격대 숙소 count:  1
489000 489999
해당가격대 숙소 count:  5
490000 490999
해당가격대 숙소 count:  4
491000 491999
492000 492999
493000 493999
해당가격대 숙소 count:  1
494000 494999
해당가격대 숙소 count:  1
495000 495999
496000 496999
497000 497999
498000 498999
499000 499999
해당가격대 숙소 count:  19
500000 500999
해당가격대 숙소 count:  19
501000 501999
해당가격대 숙소 count:  19
502000 502999
503000 503999
504000 504999
해당가격대 숙소 count:  2
505000 505999
해당가격대 숙소 count:  2
506000 506999
507000 507999
508000 508999
해당가격대 숙소 count:  1
509000 509999
해당가격대 숙소 count:  1
510000 510999
511000 511999
512000 512999
513000 513999
514000 514999
515000 515999
516000 516999
517000 517999
518000 518999
해당가격대 숙소 count:  1
519000 519999
해당가격대 숙소 count:  1
520000 520999
521000 521999
522000 522999
523000 523999
524000 524999
해당가격대 숙소 count:  1
525000 525999
해당가격대 숙소 count:  1
526000 526999
527000 527999
528000 528999
529000 529999
해당가격대 숙소 count:  1
530000 530999
해당가격대 숙소 count:  1
531000 531999
532000 532999
533000 533999
534000 534999
535000 535999
536000 536999
537000 537999
538000 538999
539000 539999
540000 540999
541000 541999
542000 542999
543000 543999
544000 544999
545000 545999
해당가격대 숙소 count:  1
546000 546999
해당가격대 숙소 count:  1
547000 547999
해당가격대 숙소 count:  1
548000 548999
549000 549999
해당가격대 숙소 count:  9
550000 550999
해당가격대 숙소 count:  9
551000 551999
552000 552999
해당가격대 숙소 count:  1
553000 553999
해당가격대 숙소 count:  1
554000 554999
555000 555999
556000 556999
557000 557999
558000 558999
559000 559999
560000 560999
해당가격대 숙소 count:  9
561000 561999
해당가격대 숙소 count:  9
562000 562999
563000 563999
564000 564999
565000 565999
566000 566999
567000 567999
568000 568999
해당가격대 숙소 count:  1
569000 569999
해당가격대 숙소 count:  1
570000 570999
571000 571999
572000 572999
573000 573999
574000 574999
575000 575999
576000 576999
577000 577999
578000 578999
579000 579999
해당가격대 숙소 count:  3
580000 580999
해당가격대 숙소 count:  3
581000 581999
582000 582999
583000 583999
584000 584999
585000 585999
586000 586999
587000 587999
588000 588999
589000 589999
해당가격대 숙소 count:  1
590000 590999
해당가격대 숙소 count:  1
591000 591999
592000 592999
593000 593999
594000 594999
595000 595999
596000 596999
597000 597999
598000 598999
599000 599999
해당가격대 숙소 count:  5
600000 600999
해당가격대 숙소 count:  5
601000 601999
602000 602999
603000 603999
604000 604999
605000 605999
606000 606999
607000 607999
608000 608999
609000 609999
610000 610999
611000 611999
612000 612999
613000 613999
614000 614999
615000 615999
616000 616999
617000 617999
618000 618999
619000 619999
620000 620999
621000 621999
622000 622999
623000 623999
624000 624999
625000 625999
626000 626999
627000 627999
628000 628999
해당가격대 숙소 count:  1
629000 629999
해당가격대 숙소 count:  1
630000 630999
해당가격대 숙소 count:  3
631000 631999
해당가격대 숙소 count:  2
632000 632999
633000 633999
634000 634999
635000 635999
636000 636999
637000 637999
638000 638999
639000 639999
640000 640999
641000 641999
642000 642999
643000 643999
644000 644999
645000 645999
646000 646999
647000 647999
648000 648999
649000 649999
해당가격대 숙소 count:  3
650000 650999
해당가격대 숙소 count:  3
651000 651999
652000 652999
653000 653999
654000 654999
655000 655999
656000 656999
657000 657999
658000 658999
659000 659999
해당가격대 숙소 count:  2
660000 660999
해당가격대 숙소 count:  2
661000 661999
662000 662999
663000 663999
664000 664999
665000 665999
666000 666999
667000 667999
668000 668999
669000 669999
670000 670999
671000 671999
672000 672999
해당가격대 숙소 count:  1
673000 673999
해당가격대 숙소 count:  1
674000 674999
675000 675999
676000 676999
677000 677999
678000 678999
679000 679999
680000 680999
681000 681999
682000 682999
683000 683999
684000 684999
685000 685999
686000 686999
687000 687999
688000 688999
689000 689999
해당가격대 숙소 count:  3
690000 690999
해당가격대 숙소 count:  3
691000 691999
692000 692999
693000 693999
694000 694999
695000 695999
696000 696999
697000 697999
698000 698999
699000 699999
해당가격대 숙소 count:  7
700000 700999
해당가격대 숙소 count:  7
701000 701999
702000 702999
703000 703999
704000 704999
705000 705999
706000 706999
707000 707999
708000 708999
709000 709999
710000 710999
711000 711999
712000 712999
713000 713999
714000 714999
715000 715999
716000 716999
717000 717999
718000 718999
719000 719999
720000 720999
721000 721999
722000 722999
723000 723999
724000 724999
725000 725999
726000 726999
727000 727999
728000 728999
729000 729999
730000 730999
731000 731999
732000 732999
733000 733999
734000 734999
735000 735999
736000 736999
737000 737999
738000 738999
해당가격대 숙소 count:  1
739000 739999
해당가격대 숙소 count:  1
740000 740999
해당가격대 숙소 count:  1
741000 741999
742000 742999
743000 743999
744000 744999
745000 745999
746000 746999
747000 747999
748000 748999
749000 749999
750000 750999
751000 751999
752000 752999
753000 753999
754000 754999
755000 755999
해당가격대 숙소 count:  1
756000 756999
해당가격대 숙소 count:  1
757000 757999
758000 758999
759000 759999
760000 760999
761000 761999
762000 762999
763000 763999
764000 764999
765000 765999
766000 766999
767000 767999
768000 768999
769000 769999
770000 770999
771000 771999
772000 772999
773000 773999
774000 774999
775000 775999
776000 776999
777000 777999
778000 778999
779000 779999
해당가격대 숙소 count:  1
780000 780999
해당가격대 숙소 count:  1
781000 781999
782000 782999
783000 783999
784000 784999
해당가격대 숙소 count:  1
785000 785999
해당가격대 숙소 count:  1
786000 786999
해당가격대 숙소 count:  1
787000 787999
788000 788999
789000 789999
790000 790999
791000 791999
792000 792999
793000 793999
794000 794999
795000 795999
796000 796999
797000 797999
798000 798999
799000 799999
해당가격대 숙소 count:  1
800000 800999
해당가격대 숙소 count:  1
801000 801999
802000 802999
803000 803999
804000 804999
805000 805999
806000 806999
807000 807999
808000 808999
809000 809999
810000 810999
811000 811999
812000 812999
813000 813999
814000 814999
815000 815999
ERR: btw 815000 and 815999|'explore_tabs'
ERR: btw 815000 and 815999|'explore_tabs'
816000 816999
817000 817999
818000 818999
819000 819999
820000 820999
821000 821999
822000 822999
823000 823999
824000 824999
825000 825999
826000 826999
827000 827999
828000 828999
829000 829999
830000 830999
831000 831999
832000 832999
833000 833999
834000 834999
835000 835999
836000 836999
837000 837999
ERR: btw 837000 and 837999|'explore_tabs'
838000 838999
839000 839999
ERR: btw 839000 and 839999|'explore_tabs'
840000 840999
841000 841999
842000 842999
843000 843999
ERR: btw 843000 and 843999|'explore_tabs'
844000 844999
845000 845999
846000 846999
847000 847999

848000 848999
849000 849999
ERR: btw 849000 and 849999|'explore_tabs'
850000 850999
851000 851999
852000 852999
853000 853999
854000 854999
855000 855999
856000 856999
857000 857999
858000 858999
859000 859999
860000 860999
861000 861999
862000 862999
863000 863999
864000 864999
865000 865999
866000 866999
ERR: btw 866000 and 866999|'explore_tabs'
867000 867999
868000 868999
869000 869999
ERR: btw 869000 and 869999|'explore_tabs'
870000 870999
ERR: btw 870000 and 870999|'explore_tabs'
871000 871999
872000 872999
873000 873999
874000 874999
875000 875999
876000 876999
877000 877999
878000 878999
879000 879999
880000 880999
881000 881999
882000 882999
ERR: btw 882000 and 882999|'explore_tabs'
ERR: btw 882000 and 882999|Expecting value: line 1 column 1 (char 0)
883000 883999
ERR: btw 883000 and 883999|'explore_tabs'
884000 884999
885000 885999
886000 886999
ERR: btw 886000 and 886999|'explore_tabs'
해당가격대 숙소 count:  1
887000 887999
해당가격대 숙소 count:  1
888000 888999
해당가격대 숙소 count:  1
889000 889999
ERR: btw 889000 and 889999|'explore_tabs'
해당가격대 숙소 count:  1
890000 890999
ERR: btw 890000 and 890999|Expecting value: line 1 column 1 (char 0)
ERR: btw 890000 and 890999|'explore_tabs'
해당가격대 숙소 count:  1
891000 891999
892000 892999
ERR: btw 892000 and 892999|'explore_tabs'
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|'explore_tabs'
해당 데이터 못가져옴
892000 892999
ERR: btw 892000 and 892999|'explore_tabs'
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
892000 892999
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|'explore_tabs'
해당 데이터 못가져옴
892000 892999
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
ERR: btw 892000 and 892999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
892000 892999
893000 893999
894000 894999
ERR: btw 894000 and 894999|Expecting value: line 1 column 1 (char 0)
ERR: btw 894000 and 894999|Expecting value: line 1 column 1 (char 0)
ERR: btw 894000 and 894999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
894000 894999
ERR: btw 894000 and 894999|'explore_tabs'
ERR: btw 894000 and 894999|Expecting value: line 1 column 1 (char 0)
ERR: btw 894000 and 894999|'explore_tabs'
해당 데이터 못가져옴
894000 894999
895000 895999
ERR: btw 895000 and 895999|Expecting value: line 1 column 1 (char 0)
896000 896999
ERR: btw 896000 and 896999|Expecting value: line 1 column 1 (char 0)
ERR: btw 896000 and 896999|Expecting value: line 1 column 1 (char 0)
897000 897999
ERR: btw 897000 and 897999|Expecting value: line 1 column 1 (char 0)
ERR: btw 897000 and 897999|Expecting value: line 1 column 1 (char 0)
ERR: btw 897000 and 897999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
897000 897999
ERR: btw 897000 and 897999|Expecting value: line 1 column 1 (char 0)
ERR: btw 897000 and 897999|Expecting value: line 1 column 1 (char 0)
ERR: btw 897000 and 897999|'explore_tabs'
해당 데이터 못가져옴
897000 897999
898000 898999
899000 899999
ERR: btw 899000 and 899999|Expecting value: line 1 column 1 (char 0)
ERR: btw 899000 and 899999|Expecting value: line 1 column 1 (char 0)
ERR: btw 899000 and 899999|'explore_tabs'
해당 데이터 못가져옴
899000 899999
ERR: btw 899000 and 899999|'explore_tabs'
해당가격대 숙소 count:  2
900000 900999
ERR: btw 900000 and 900999|Expecting value: line 1 column 1 (char 0)
ERR: btw 900000 and 900999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  2
901000 901999
902000 902999
903000 903999
ERR: btw 903000 and 903999|Expecting value: line 1 column 1 (char 0)
ERR: btw 903000 and 903999|Expecting value: line 1 column 1 (char 0)
ERR: btw 903000 and 903999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
903000 903999
904000 904999
ERR: btw 904000 and 904999|Expecting value: line 1 column 1 (char 0)
ERR: btw 904000 and 904999|'explore_tabs'
ERR: btw 904000 and 904999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
904000 904999
905000 905999
ERR: btw 905000 and 905999|'explore_tabs'
ERR: btw 905000 and 905999|'explore_tabs'
906000 906999
907000 907999
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
907000 907999
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
907000 907999
ERR: btw 907000 and 907999|Expecting value: line 1 column 1 (char 0)
908000 908999
909000 909999
ERR: btw 909000 and 909999|Expecting value: line 1 column 1 (char 0)
ERR: btw 909000 and 909999|'explore_tabs'
ERR: btw 909000 and 909999|'explore_tabs'
해당 데이터 못가져옴
909000 909999
ERR: btw 909000 and 909999|'explore_tabs'
910000 910999
ERR: btw 910000 and 910999|Expecting value: line 1 column 1 (char 0)
ERR: btw 910000 and 910999|Expecting value: line 1 column 1 (char 0)
ERR: btw 910000 and 910999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
910000 910999
911000 911999
ERR: btw 911000 and 911999|Expecting value: line 1 column 1 (char 0)
ERR: btw 911000 and 911999|Expecting value: line 1 column 1 (char 0)
ERR: btw 911000 and 911999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
911000 911999
ERR: btw 911000 and 911999|'explore_tabs'
ERR: btw 911000 and 911999|Expecting value: line 1 column 1 (char 0)
ERR: btw 911000 and 911999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
911000 911999
912000 912999
ERR: btw 912000 and 912999|Expecting value: line 1 column 1 (char 0)
ERR: btw 912000 and 912999|'explore_tabs'
ERR: btw 912000 and 912999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
912000 912999
ERR: btw 912000 and 912999|Expecting value: line 1 column 1 (char 0)
ERR: btw 912000 and 912999|'explore_tabs'
ERR: btw 912000 and 912999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
912000 912999
ERR: btw 912000 and 912999|Expecting value: line 1 column 1 (char 0)
913000 913999
ERR: btw 913000 and 913999|'explore_tabs'
ERR: btw 913000 and 913999|Expecting value: line 1 column 1 (char 0)
ERR: btw 913000 and 913999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
913000 913999
ERR: btw 913000 and 913999|Expecting value: line 1 column 1 (char 0)
914000 914999
ERR: btw 914000 and 914999|Expecting value: line 1 column 1 (char 0)
ERR: btw 914000 and 914999|Expecting value: line 1 column 1 (char 0)
915000 915999
916000 916999
ERR: btw 916000 and 916999|Expecting value: line 1 column 1 (char 0)
ERR: btw 916000 and 916999|'explore_tabs'
ERR: btw 916000 and 916999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
916000 916999
ERR: btw 916000 and 916999|Expecting value: line 1 column 1 (char 0)
ERR: btw 916000 and 916999|'explore_tabs'
ERR: btw 916000 and 916999|'explore_tabs'
해당 데이터 못가져옴
916000 916999
ERR: btw 916000 and 916999|Expecting value: line 1 column 1 (char 0)
ERR: btw 916000 and 916999|'explore_tabs'
ERR: btw 916000 and 916999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
916000 916999
917000 917999
ERR: btw 917000 and 917999|Expecting value: line 1 column 1 (char 0)
918000 918999
ERR: btw 918000 and 918999|Expecting value: line 1 column 1 (char 0)
ERR: btw 918000 and 918999|Expecting value: line 1 column 1 (char 0)
ERR: btw 918000 and 918999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
918000 918999
919000 919999
ERR: btw 919000 and 919999|Expecting value: line 1 column 1 (char 0)
ERR: btw 919000 and 919999|'explore_tabs'
ERR: btw 919000 and 919999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
919000 919999
ERR: btw 919000 and 919999|'explore_tabs'
ERR: btw 919000 and 919999|Expecting value: line 1 column 1 (char 0)
ERR: btw 919000 and 919999|'explore_tabs'
해당 데이터 못가져옴
919000 919999
ERR: btw 919000 and 919999|Expecting value: line 1 column 1 (char 0)
ERR: btw 919000 and 919999|'explore_tabs'
ERR: btw 919000 and 919999|'explore_tabs'

해당 데이터 못가져옴
919000 919999
920000 920999
ERR: btw 920000 and 920999|Expecting value: line 1 column 1 (char 0)
ERR: btw 920000 and 920999|Expecting value: line 1 column 1 (char 0)
921000 921999
ERR: btw 921000 and 921999|Expecting value: line 1 column 1 (char 0)
ERR: btw 921000 and 921999|Expecting value: line 1 column 1 (char 0)
922000 922999
923000 923999
924000 924999
925000 925999
ERR: btw 925000 and 925999|Expecting value: line 1 column 1 (char 0)
926000 926999
927000 927999
ERR: btw 927000 and 927999|Expecting value: line 1 column 1 (char 0)
ERR: btw 927000 and 927999|Expecting value: line 1 column 1 (char 0)
ERR: btw 927000 and 927999|'explore_tabs'
해당 데이터 못가져옴
927000 927999
ERR: btw 927000 and 927999|Expecting value: line 1 column 1 (char 0)
ERR: btw 927000 and 927999|Expecting value: line 1 column 1 (char 0)
ERR: btw 927000 and 927999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
927000 927999
928000 928999
ERR: btw 928000 and 928999|'explore_tabs'
ERR: btw 928000 and 928999|Expecting value: line 1 column 1 (char 0)
ERR: btw 928000 and 928999|'explore_tabs'
해당 데이터 못가져옴
928000 928999
ERR: btw 928000 and 928999|Expecting value: line 1 column 1 (char 0)
ERR: btw 928000 and 928999|'explore_tabs'
929000 929999
930000 930999
ERR: btw 930000 and 930999|Expecting value: line 1 column 1 (char 0)
ERR: btw 930000 and 930999|'explore_tabs'
ERR: btw 930000 and 930999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
930000 930999
931000 931999
ERR: btw 931000 and 931999|Expecting value: line 1 column 1 (char 0)
932000 932999
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
932000 932999
ERR: btw 932000 and 932999|'explore_tabs'
ERR: btw 932000 and 932999|'explore_tabs'
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
932000 932999
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
ERR: btw 932000 and 932999|Expecting value: line 1 column 1 (char 0)
933000 933999
ERR: btw 933000 and 933999|Expecting value: line 1 column 1 (char 0)
ERR: btw 933000 and 933999|Expecting value: line 1 column 1 (char 0)
ERR: btw 933000 and 933999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
933000 933999
해당가격대 숙소 count:  1
934000 934999
ERR: btw 934000 and 934999|Expecting value: line 1 column 1 (char 0)
ERR: btw 934000 and 934999|Expecting value: line 1 column 1 (char 0)
ERR: btw 934000 and 934999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
934000 934999
ERR: btw 934000 and 934999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  1
935000 935999
ERR: btw 935000 and 935999|'explore_tabs'
ERR: btw 935000 and 935999|Expecting value: line 1 column 1 (char 0)
ERR: btw 935000 and 935999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
935000 935999
936000 936999
ERR: btw 936000 and 936999|Expecting value: line 1 column 1 (char 0)
ERR: btw 936000 and 936999|Expecting value: line 1 column 1 (char 0)
937000 937999
938000 938999
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
938000 938999
ERR: btw 938000 and 938999|'explore_tabs'
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
938000 938999
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
ERR: btw 938000 and 938999|Expecting value: line 1 column 1 (char 0)
ERR: btw 938000 and 938999|'explore_tabs'
해당 데이터 못가져옴
938000 938999
939000 939999
ERR: btw 939000 and 939999|'explore_tabs'
ERR: btw 939000 and 939999|'explore_tabs'
ERR: btw 939000 and 939999|'explore_tabs'
해당 데이터 못가져옴
939000 939999
940000 940999
ERR: btw 940000 and 940999|'explore_tabs'
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
940000 940999
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
940000 940999
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
940000 940999
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
940000 940999
ERR: btw 940000 and 940999|Expecting value: line 1 column 1 (char 0)
941000 941999
ERR: btw 941000 and 941999|Expecting value: line 1 column 1 (char 0)
ERR: btw 941000 and 941999|Expecting value: line 1 column 1 (char 0)
ERR: btw 941000 and 941999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
941000 941999
ERR: btw 941000 and 941999|Expecting value: line 1 column 1 (char 0)
942000 942999
ERR: btw 942000 and 942999|Expecting value: line 1 column 1 (char 0)
943000 943999
944000 944999
945000 945999
946000 946999
ERR: btw 946000 and 946999|Expecting value: line 1 column 1 (char 0)
947000 947999
948000 948999
ERR: btw 948000 and 948999|Expecting value: line 1 column 1 (char 0)
ERR: btw 948000 and 948999|Expecting value: line 1 column 1 (char 0)
ERR: btw 948000 and 948999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
948000 948999
949000 949999
ERR: btw 949000 and 949999|Expecting value: line 1 column 1 (char 0)
ERR: btw 949000 and 949999|'explore_tabs'
ERR: btw 949000 and 949999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
949000 949999
950000 950999
ERR: btw 950000 and 950999|Expecting value: line 1 column 1 (char 0)
ERR: btw 950000 and 950999|'explore_tabs'
951000 951999
ERR: btw 951000 and 951999|Expecting value: line 1 column 1 (char 0)
ERR: btw 951000 and 951999|Expecting value: line 1 column 1 (char 0)
ERR: btw 951000 and 951999|'explore_tabs'
해당 데이터 못가져옴
951000 951999
ERR: btw 951000 and 951999|Expecting value: line 1 column 1 (char 0)
952000 952999
ERR: btw 952000 and 952999|Expecting value: line 1 column 1 (char 0)
953000 953999
ERR: btw 953000 and 953999|Expecting value: line 1 column 1 (char 0)
954000 954999
955000 955999
ERR: btw 955000 and 955999|Expecting value: line 1 column 1 (char 0)
ERR: btw 955000 and 955999|Expecting value: line 1 column 1 (char 0)
956000 956999
ERR: btw 956000 and 956999|Expecting value: line 1 column 1 (char 0)
ERR: btw 956000 and 956999|Expecting value: line 1 column 1 (char 0)
ERR: btw 956000 and 956999|'explore_tabs'
해당 데이터 못가져옴
956000 956999
ERR: btw 956000 and 956999|Expecting value: line 1 column 1 (char 0)
ERR: btw 956000 and 956999|'explore_tabs'
ERR: btw 956000 and 956999|'explore_tabs'
해당 데이터 못가져옴
956000 956999
ERR: btw 956000 and 956999|Expecting value: line 1 column 1 (char 0)
ERR: btw 956000 and 956999|Expecting value: line 1 column 1 (char 0)
957000 957999
ERR: btw 957000 and 957999|'explore_tabs'
ERR: btw 957000 and 957999|Expecting value: line 1 column 1 (char 0)
958000 958999
ERR: btw 958000 and 958999|Expecting value: line 1 column 1 (char 0)
ERR: btw 958000 and 958999|Expecting value: line 1 column 1 (char 0)
ERR: btw 958000 and 958999|'explore_tabs'
해당 데이터 못가져옴
958000 958999
ERR: btw 958000 and 958999|Expecting value: line 1 column 1 (char 0)
959000 959999
ERR: btw 959000 and 959999|Expecting value: line 1 column 1 (char 0)
960000 960999
961000 961999
962000 962999
ERR: btw 962000 and 962999|Expecting value: line 1 column 1 (char 0)
ERR: btw 962000 and 962999|Expecting value: line 1 column 1 (char 0)
ERR: btw 962000 and 962999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
962000 962999
ERR: btw 962000 and 962999|Expecting value: line 1 column 1 (char 0)
ERR: btw 962000 and 962999|Expecting value: line 1 column 1 (char 0)
963000 963999
ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)
ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)

ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
963000 963999
ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)
ERR: btw 963000 and 963999|'explore_tabs'
ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
963000 963999
ERR: btw 963000 and 963999|Expecting value: line 1 column 1 (char 0)
964000 964999
ERR: btw 964000 and 964999|Expecting value: line 1 column 1 (char 0)
965000 965999
ERR: btw 965000 and 965999|'explore_tabs'
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
965000 965999
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
965000 965999
ERR: btw 965000 and 965999|Expecting value: line 1 column 1 (char 0)
966000 966999
ERR: btw 966000 and 966999|Expecting value: line 1 column 1 (char 0)
ERR: btw 966000 and 966999|'explore_tabs'
967000 967999
968000 968999
969000 969999
970000 970999
ERR: btw 970000 and 970999|Expecting value: line 1 column 1 (char 0)
971000 971999
ERR: btw 971000 and 971999|'explore_tabs'
972000 972999
ERR: btw 972000 and 972999|'explore_tabs'
ERR: btw 972000 and 972999|'explore_tabs'
ERR: btw 972000 and 972999|'explore_tabs'
해당 데이터 못가져옴
972000 972999
ERR: btw 972000 and 972999|Expecting value: line 1 column 1 (char 0)
973000 973999
974000 974999
975000 975999
976000 976999
ERR: btw 976000 and 976999|Expecting value: line 1 column 1 (char 0)
ERR: btw 976000 and 976999|'explore_tabs'
ERR: btw 976000 and 976999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
976000 976999
ERR: btw 976000 and 976999|'explore_tabs'
ERR: btw 976000 and 976999|Expecting value: line 1 column 1 (char 0)
ERR: btw 976000 and 976999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
976000 976999
977000 977999
978000 978999
ERR: btw 978000 and 978999|'explore_tabs'
ERR: btw 978000 and 978999|Expecting value: line 1 column 1 (char 0)
ERR: btw 978000 and 978999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
978000 978999
979000 979999
980000 980999
ERR: btw 980000 and 980999|Expecting value: line 1 column 1 (char 0)
981000 981999
982000 982999
983000 983999
984000 984999
985000 985999
ERR: btw 985000 and 985999|Expecting value: line 1 column 1 (char 0)
986000 986999
987000 987999
988000 988999
ERR: btw 988000 and 988999|Expecting value: line 1 column 1 (char 0)
989000 989999
990000 990999
991000 991999
992000 992999
ERR: btw 992000 and 992999|Expecting value: line 1 column 1 (char 0)
ERR: btw 992000 and 992999|'explore_tabs'
993000 993999
994000 994999
ERR: btw 994000 and 994999|Expecting value: line 1 column 1 (char 0)
ERR: btw 994000 and 994999|Expecting value: line 1 column 1 (char 0)
ERR: btw 994000 and 994999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
994000 994999
ERR: btw 994000 and 994999|'explore_tabs'
ERR: btw 994000 and 994999|'explore_tabs'
ERR: btw 994000 and 994999|'explore_tabs'
해당 데이터 못가져옴
994000 994999
ERR: btw 994000 and 994999|Expecting value: line 1 column 1 (char 0)
ERR: btw 994000 and 994999|Expecting value: line 1 column 1 (char 0)
995000 995999
ERR: btw 995000 and 995999|'explore_tabs'
996000 996999
ERR: btw 996000 and 996999|'explore_tabs'
ERR: btw 996000 and 996999|Expecting value: line 1 column 1 (char 0)
해당가격대 숙소 count:  1
997000 997999
ERR: btw 997000 and 997999|'explore_tabs'
ERR: btw 997000 and 997999|'explore_tabs'
ERR: btw 997000 and 997999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
997000 997999
해당가격대 숙소 count:  1
998000 998999
ERR: btw 998000 and 998999|Expecting value: line 1 column 1 (char 0)
ERR: btw 998000 and 998999|'explore_tabs'
ERR: btw 998000 and 998999|Expecting value: line 1 column 1 (char 0)
해당 데이터 못가져옴
998000 998999
해당가격대 숙소 count:  2
999000 999999
해당가격대 숙소 count:  8
CPU times: user 1min 38s, sys: 4.26 s, total: 1min 42s
Wall time: 46min 29s

In [45]:
len(home.keys()) # 100원 단위 전체

14650

In [21]:
len(home.keys()) # 100원 단위 30000~33000

679